#!/usr/bin/env python3
"""
VC Seed Batch 2 — additional curated records to reach 500+ total
"""
import os
import requests

SUPABASE_URL = os.environ.get("SUPABASE_URL", "https://tnloaqibvtekphwjehwc.supabase.co")
SERVICE_ROLE_KEY = os.environ.get("SUPABASE_SERVICE_ROLE_KEY", "")


def upsert_vcs(records):
    if not records:
        return 0
    url = f"{SUPABASE_URL}/rest/v1/vcs?on_conflict=name"
    headers = {
        "apikey": SERVICE_ROLE_KEY,
        "Authorization": f"Bearer {SERVICE_ROLE_KEY}",
        "Content-Type": "application/json",
        "Prefer": "resolution=merge-duplicates,return=minimal",
    }
    resp = requests.post(url, headers=headers, json=records, timeout=30)
    if resp.status_code not in (200, 201):
        print(f"  [WARN] {resp.status_code}: {resp.text[:200]}")
        return 0
    return len(records)


BATCH2 = [
    # Israel / Tel Aviv
    {"name": "Team8", "website": "https://team8.vc", "focus_sectors": ["Cybersecurity", "AI", "Fintech", "Enterprise"], "stage_preference": ["seed", "series-a"], "check_size_min": 1000, "check_size_max": 20000, "geo_focus": ["Israel", "Global"], "notable_portfolio": [], "description": "Israeli company-builder and VC fund focused on cybersecurity and AI.", "source": "curated"},
    {"name": "Viola Ventures", "website": "https://www.viola-group.com/ventures", "focus_sectors": ["Enterprise SaaS", "Cybersecurity", "AI", "Deep Tech"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 1000, "check_size_max": 20000, "geo_focus": ["Israel"], "notable_portfolio": [], "description": "Israel's leading tech VC firm.", "source": "curated"},
    {"name": "OurCrowd", "website": "https://www.ourcrowd.com", "focus_sectors": ["Technology", "Healthcare", "AI", "Fintech"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 250, "check_size_max": 10000, "geo_focus": ["Israel", "Global"], "notable_portfolio": [], "description": "Jerusalem-based venture investing platform and VC.", "source": "curated"},
    {"name": "Pitango Venture Capital", "website": "https://www.pitango.com", "focus_sectors": ["Technology", "Healthcare", "SaaS"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 1000, "check_size_max": 30000, "geo_focus": ["Israel"], "notable_portfolio": [], "description": "One of Israel's largest and most active venture capital firms.", "source": "curated"},
    {"name": "Jerusalem Venture Partners (JVP)", "website": "https://jvpvc.com", "focus_sectors": ["Cybersecurity", "Media Tech", "AI", "Enterprise"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 1000, "check_size_max": 20000, "geo_focus": ["Israel"], "notable_portfolio": ["Tufin", "CyberArk", "NICE Systems"], "description": "Israeli VC focused on disruptive tech companies.", "source": "curated"},
    {"name": "83North", "website": "https://www.83north.com", "focus_sectors": ["Enterprise SaaS", "Consumer", "Fintech", "Deep Tech"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 1000, "check_size_max": 30000, "geo_focus": ["Israel", "Europe"], "notable_portfolio": [], "description": "European and Israeli early-stage technology investor.", "source": "curated"},

    # Southeast Asia / Asia Pacific
    {"name": "East Ventures", "website": "https://east.vc", "focus_sectors": ["Consumer", "Fintech", "SaaS", "Healthcare"], "stage_preference": ["seed", "series-a"], "check_size_min": 250, "check_size_max": 5000, "geo_focus": ["Southeast Asia", "Indonesia"], "notable_portfolio": ["Tokopedia", "Traveloka", "Ruangguru"], "description": "The most active early-stage VC in Southeast Asia.", "source": "curated"},
    {"name": "Sequoia Capital India", "website": "https://www.sequoiacap.com/india", "focus_sectors": ["Technology", "Consumer", "Fintech", "Healthcare"], "stage_preference": ["seed", "series-a", "series-b", "growth"], "check_size_min": 500, "check_size_max": 100000, "geo_focus": ["India", "Southeast Asia"], "notable_portfolio": ["Byju's", "OYO", "Meesho", "CRED"], "description": "Sequoia Capital's India and Southeast Asia operations.", "source": "curated"},
    {"name": "Accel India", "website": "https://www.accel.com/india", "focus_sectors": ["Enterprise SaaS", "Consumer", "Fintech"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 500, "check_size_max": 30000, "geo_focus": ["India"], "notable_portfolio": ["Flipkart", "Swiggy", "Urban Ladder"], "description": "Accel's India-focused operations.", "source": "curated"},
    {"name": "Nexus Venture Partners", "website": "https://www.nexusvp.com", "focus_sectors": ["SaaS", "Fintech", "Consumer", "Healthcare"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 500, "check_size_max": 20000, "geo_focus": ["India", "United States"], "notable_portfolio": ["Snapdeal", "Housing.com", "Delhivery"], "description": "India and US focused cross-border VC.", "source": "curated"},
    {"name": "Blume Ventures", "website": "https://www.blume.vc", "focus_sectors": ["SaaS", "Consumer", "Fintech", "Deep Tech"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 100, "check_size_max": 2000, "geo_focus": ["India"], "notable_portfolio": ["Unacademy", "Dunzo", "Slice"], "description": "India's leading seed-stage venture fund.", "source": "curated"},
    {"name": "Kalaari Capital", "website": "https://www.kalaari.com", "focus_sectors": ["Consumer", "Fintech", "Enterprise SaaS"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 500, "check_size_max": 10000, "geo_focus": ["India"], "notable_portfolio": ["Dream11", "Myntra", "Snapdeal"], "description": "India-focused early and growth stage VC.", "source": "curated"},
    {"name": "Jungle Ventures", "website": "https://www.jungle.vc", "focus_sectors": ["Consumer", "Fintech", "B2B SaaS"], "stage_preference": ["series-a", "series-b"], "check_size_min": 2000, "check_size_max": 20000, "geo_focus": ["Southeast Asia"], "notable_portfolio": [], "description": "Singapore-based venture fund focused on Southeast Asia.", "source": "curated"},
    {"name": "Golden Gate Ventures", "website": "https://goldengate.vc", "focus_sectors": ["Consumer", "Fintech", "Marketplace"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["Southeast Asia"], "notable_portfolio": [], "description": "Southeast Asia seed and Series A investor.", "source": "curated"},
    {"name": "500 Southeast Asia", "website": "https://500.co/southeast-asia", "focus_sectors": ["Technology", "Fintech", "Consumer"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 100, "check_size_max": 1000, "geo_focus": ["Southeast Asia"], "notable_portfolio": [], "description": "500 Global's Southeast Asia focused fund.", "source": "curated"},

    # Africa
    {"name": "Partech Africa", "website": "https://partechpartners.com/africa", "focus_sectors": ["Fintech", "Agtech", "Health Tech", "B2B SaaS"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 500, "check_size_max": 20000, "geo_focus": ["Africa"], "notable_portfolio": ["Wave", "Yoco", "Talabat"], "description": "Largest African VC fund by portfolio size.", "source": "curated"},
    {"name": "TLcom Capital", "website": "https://www.tlcom.co.uk", "focus_sectors": ["Fintech", "Logistics", "Health Tech", "B2B"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 500, "check_size_max": 10000, "geo_focus": ["Sub-Saharan Africa"], "notable_portfolio": ["Andela", "Twiga Foods"], "description": "Sub-Saharan Africa focused early-stage VC.", "source": "curated"},
    {"name": "Ventures Platform", "website": "https://venturesplatform.com", "focus_sectors": ["Fintech", "Healthcare", "Agtech", "Logistics"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 50, "check_size_max": 1000, "geo_focus": ["West Africa", "Nigeria"], "notable_portfolio": [], "description": "Nigeria-based early-stage VC fund.", "source": "curated"},
    {"name": "CcHub", "website": "https://cchubnigeria.com", "focus_sectors": ["Technology", "Social Impact", "Fintech"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 25, "check_size_max": 500, "geo_focus": ["West Africa", "Nigeria"], "notable_portfolio": [], "description": "Nigeria's largest technology innovation hub and seed investor.", "source": "curated"},
    {"name": "4DX Ventures", "website": "https://4dxventures.com", "focus_sectors": ["Fintech", "Healthcare", "Agriculture", "SME Enablement"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["Africa"], "notable_portfolio": [], "description": "Africa-focused tech VC with cross-continental approach.", "source": "curated"},

    # Nordic / Scandinavia
    {"name": "Creandum", "website": "https://creandum.com", "focus_sectors": ["SaaS", "Consumer", "Fintech", "Deep Tech"], "stage_preference": ["seed", "series-a"], "check_size_min": 1000, "check_size_max": 15000, "geo_focus": ["Scandinavia", "Europe"], "notable_portfolio": ["Spotify", "iZettle", "Kahoot", "Klarna"], "description": "Leading Nordic venture capital firm.", "source": "curated"},
    {"name": "byFounders", "website": "https://byfounders.vc", "focus_sectors": ["SaaS", "Consumer", "Developer Tools", "Deep Tech"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 250, "check_size_max": 3000, "geo_focus": ["Scandinavia", "Europe"], "notable_portfolio": [], "description": "Founder-led VC fund for Nordic and Baltic startups.", "source": "curated"},
    {"name": "Inventure", "website": "https://inventure.fi", "focus_sectors": ["SaaS", "Fintech", "Healthtech", "Deep Tech"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 10000, "geo_focus": ["Finland", "Scandinavia"], "notable_portfolio": [], "description": "Finland and Scandinavia focused early-stage VC.", "source": "curated"},

    # UK Specific
    {"name": "Octopus Ventures", "website": "https://octopusventures.com", "focus_sectors": ["Healthcare", "SaaS", "Fintech", "Deep Tech", "Consumer"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 500, "check_size_max": 20000, "geo_focus": ["United Kingdom", "Europe"], "notable_portfolio": [], "description": "One of the most active VCs in the UK.", "source": "curated"},
    {"name": "LocalGlobe", "website": "https://localglobe.vc", "focus_sectors": ["Consumer", "Enterprise SaaS", "Deep Tech", "Climate"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 250, "check_size_max": 3000, "geo_focus": ["United Kingdom", "Europe"], "notable_portfolio": ["Robinhood", "Figma", "Transferwise"], "description": "London-based seed-stage VC backing exceptional founders early.", "source": "curated"},
    {"name": "Episode 1 Ventures", "website": "https://www.episode1.com", "focus_sectors": ["SaaS", "Marketplace", "Consumer"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 150, "check_size_max": 2000, "geo_focus": ["United Kingdom"], "notable_portfolio": [], "description": "UK-based seed investor focused on first checks.", "source": "curated"},
    {"name": "Notion Capital", "website": "https://notion.vc", "focus_sectors": ["Enterprise SaaS", "B2B", "Fintech"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 7000, "geo_focus": ["Europe", "United Kingdom"], "notable_portfolio": [], "description": "European B2B SaaS focused VC.", "source": "curated"},
    {"name": "Hoxton Ventures", "website": "https://www.hoxtonventures.com", "focus_sectors": ["Consumer", "Enterprise", "Deep Tech"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["Europe", "United Kingdom"], "notable_portfolio": ["Babylon Health", "Lovecrafts", "Curve"], "description": "London-based early-stage venture capital.", "source": "curated"},

    # France / Southern Europe
    {"name": "Partech Ventures", "website": "https://partechpartners.com", "focus_sectors": ["SaaS", "Consumer", "Fintech", "Deep Tech"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 500, "check_size_max": 50000, "geo_focus": ["Europe", "United States", "Africa"], "notable_portfolio": [], "description": "Pan-European and global VC firm.", "source": "curated"},
    {"name": "Kima Ventures", "website": "https://www.kimaventures.com", "focus_sectors": ["Technology", "SaaS", "Consumer", "Fintech"], "stage_preference": ["pre-seed"], "check_size_min": 100, "check_size_max": 500, "geo_focus": ["Global"], "notable_portfolio": [], "description": "The world's most active seed fund, backing 150+ companies per year.", "source": "curated"},
    {"name": "Idinvest Partners", "website": "https://www.idinvest.com", "focus_sectors": ["Technology", "Healthcare", "Consumer", "Energy"], "stage_preference": ["series-a", "series-b", "growth"], "check_size_min": 5000, "check_size_max": 50000, "geo_focus": ["France", "Europe"], "notable_portfolio": [], "description": "French mid-market private equity and VC firm.", "source": "curated"},

    # US Sector / Stage Specialists continued
    {"name": "Alumni Ventures", "website": "https://av.vc", "focus_sectors": ["Technology", "Healthcare", "Consumer", "Fintech"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 100, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Alumni-network-based VC fund with multiple university-branded funds.", "source": "curated"},
    {"name": "Operator Collective", "website": "https://operatorcollective.com", "focus_sectors": ["Enterprise SaaS", "Marketplace", "Fintech"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Enterprise VC built by operators for founders.", "source": "curated"},
    {"name": "Mango Capital", "website": "https://mangocapital.com", "focus_sectors": ["Consumer", "Enterprise", "Health"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 100, "check_size_max": 1000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Seed-stage VC fund for underrepresented founders.", "source": "curated"},
    {"name": "Susa Ventures", "website": "https://www.susaventures.com", "focus_sectors": ["Data", "SaaS", "Healthcare", "Fintech", "Consumer"], "stage_preference": ["seed"], "check_size_min": 250, "check_size_max": 3000, "geo_focus": ["United States"], "notable_portfolio": ["Robinhood", "Premise Data", "Rigetti Computing"], "description": "San Francisco based seed-stage VC.", "source": "curated"},
    {"name": "Bain Capital Ventures", "website": "https://baincapitalventures.com", "focus_sectors": ["SaaS", "Infrastructure", "Healthcare", "Fintech"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 2000, "check_size_max": 50000, "geo_focus": ["United States"], "notable_portfolio": ["DocuSign", "LinkedIn", "Jet.com", "SurveyMonkey"], "description": "VC arm of Bain Capital.", "source": "curated"},
    {"name": "Comcast NBCUniversal LIFT Labs", "website": "https://liftlabs.comcast.com", "focus_sectors": ["Media", "Entertainment", "Broadband", "Smart Home"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Comcast NBCU's startup accelerator and venture arm.", "source": "curated"},
    {"name": "Closed Loop Partners", "website": "https://www.closedlooppartners.com", "focus_sectors": ["Circular Economy", "Sustainability", "Consumer Goods", "Retail Tech"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 1000, "check_size_max": 20000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Circular economy and sustainability focused investment firm.", "source": "curated"},
    {"name": "Construct Capital", "website": "https://constructcap.com", "focus_sectors": ["Industrial Tech", "Supply Chain", "Logistics", "Aerospace"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 10000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Seed and Series A investor in the industrialization of America.", "source": "curated"},
    {"name": "Footwork VC", "website": "https://footwork.vc", "focus_sectors": ["Consumer", "Fintech", "SaaS"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Consumer and fintech focused seed VC.", "source": "curated"},
    {"name": "Laconia Capital Group", "website": "https://laconiacapitalgroup.com", "focus_sectors": ["B2B SaaS", "Consumer", "Healthcare"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 100, "check_size_max": 1000, "geo_focus": ["New York", "United States"], "notable_portfolio": [], "description": "NYC seed-stage VC fund.", "source": "curated"},
    {"name": "Compound", "website": "https://compound.vc", "focus_sectors": ["Enterprise SaaS", "AI", "Developer Tools"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Enterprise tech investor backing repeat founders.", "source": "curated"},
    {"name": "Inspired Capital", "website": "https://inspiredcapital.com", "focus_sectors": ["Consumer", "Fintech", "Healthcare", "Future of Work"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Early-stage VC with portfolio of mission-driven companies.", "source": "curated"},
    {"name": "Benenson Capital Partners", "website": "https://benensoncp.com", "focus_sectors": ["Technology", "Consumer", "Media"], "stage_preference": ["seed", "series-a"], "check_size_min": 250, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Multi-generational VC and family office.", "source": "curated"},
    {"name": "Crosscut Ventures", "website": "https://crosscutventures.com", "focus_sectors": ["Consumer", "Enterprise SaaS", "Fintech", "Media"], "stage_preference": ["seed", "series-a"], "check_size_min": 250, "check_size_max": 5000, "geo_focus": ["Los Angeles", "United States"], "notable_portfolio": [], "description": "LA-based seed and Series A VC.", "source": "curated"},
    {"name": "Wonder Ventures", "website": "https://wonder.ventures", "focus_sectors": ["Consumer", "Enterprise", "Marketplace"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 100, "check_size_max": 1000, "geo_focus": ["Los Angeles", "United States"], "notable_portfolio": [], "description": "LA-focused seed micro-VC.", "source": "curated"},
    {"name": "Mucker Capital", "website": "https://muckercapital.com", "focus_sectors": ["SaaS", "Enterprise", "Consumer", "Marketplace"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 250, "check_size_max": 3000, "geo_focus": ["Los Angeles", "United States"], "notable_portfolio": [], "description": "Los Angeles based seed accelerator and VC.", "source": "curated"},
    {"name": "TenOneTen Ventures", "website": "https://www.tenoneten.net", "focus_sectors": ["SaaS", "Consumer", "Marketplace", "Media"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 100, "check_size_max": 1000, "geo_focus": ["Los Angeles", "United States"], "notable_portfolio": [], "description": "Los Angeles and New York focused micro-VC.", "source": "curated"},
    {"name": "Pritzker Group Venture Capital", "website": "https://pritzkergroup.com/venture-capital", "focus_sectors": ["Enterprise SaaS", "Consumer", "Healthcare", "Fintech"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 1000, "check_size_max": 20000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Chicago-based venture arm of the Pritzker family office.", "source": "curated"},
    {"name": "Math Venture Partners", "website": "https://mathventurespartners.com", "focus_sectors": ["Enterprise SaaS", "Fintech", "AI"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["Midwest", "Chicago", "United States"], "notable_portfolio": [], "description": "Chicago-based early-stage VC.", "source": "curated"},
    {"name": "Hyde Park Venture Partners", "website": "https://www.hydeparkventure.com", "focus_sectors": ["B2B SaaS", "Healthcare", "Fintech"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["Midwest", "Chicago", "United States"], "notable_portfolio": [], "description": "Chicago-based B2B tech seed investor.", "source": "curated"},
    {"name": "Cultivation Capital", "website": "https://cultivationcapital.com", "focus_sectors": ["Agtech", "Healthcare", "SaaS", "Enterprise"], "stage_preference": ["seed", "series-a"], "check_size_min": 250, "check_size_max": 5000, "geo_focus": ["Midwest", "St. Louis", "United States"], "notable_portfolio": [], "description": "St. Louis based early-stage VC with agtech and healthcare focus.", "source": "curated"},
    {"name": "Grayhawk Capital", "website": "https://grayhawkcapital.com", "focus_sectors": ["Technology", "Healthcare", "Consumer", "SaaS"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["Southwest", "Arizona", "United States"], "notable_portfolio": [], "description": "Arizona-based early-stage VC.", "source": "curated"},
    {"name": "Knoll Ventures", "website": "https://knollventures.com", "focus_sectors": ["Technology", "SaaS", "Fintech"], "stage_preference": ["seed", "series-a"], "check_size_min": 250, "check_size_max": 3000, "geo_focus": ["Southeast", "United States"], "notable_portfolio": [], "description": "Southeast US focused seed VC.", "source": "curated"},
    {"name": "BIP Ventures", "website": "https://bipventures.vc", "focus_sectors": ["Technology", "SaaS", "Healthcare", "Fintech"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["Southeast", "Atlanta", "United States"], "notable_portfolio": [], "description": "Atlanta-based early-stage technology investor.", "source": "curated"},
    {"name": "Panoramic Ventures", "website": "https://panoramicventures.com", "focus_sectors": ["Technology", "SaaS", "Fintech", "Healthcare"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["Southeast", "United States"], "notable_portfolio": [], "description": "Southeast US's leading early-stage VC.", "source": "curated"},
    {"name": "Cottonwood Technology Fund", "website": "https://cottonwoodtechfund.com", "focus_sectors": ["Deep Tech", "AI", "Hardware", "IoT"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 100, "check_size_max": 1000, "geo_focus": ["Mountain West", "United States"], "notable_portfolio": [], "description": "Mountain West deep tech seed fund.", "source": "curated"},

    # Specialized Impact / Sector VCs
    {"name": "Kapor Capital", "website": "https://www.kaporcapital.com", "focus_sectors": ["EdTech", "Health Tech", "Fintech", "Future of Work"], "stage_preference": ["seed", "series-a"], "check_size_min": 250, "check_size_max": 3000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Impact-driven VC investing in tech for underrepresented communities.", "source": "curated"},
    {"name": "Reach Capital", "website": "https://reachcapital.com", "focus_sectors": ["EdTech", "Future of Work", "Human Capital"], "stage_preference": ["seed", "series-a"], "check_size_min": 250, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Dedicated EdTech venture fund.", "source": "curated"},
    {"name": "NewSchools Venture Fund", "website": "https://www.newschools.org", "focus_sectors": ["EdTech", "K-12 Education"], "stage_preference": ["seed", "series-a"], "check_size_min": 250, "check_size_max": 3000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Non-profit venture philanthropy for education innovation.", "source": "curated"},
    {"name": "Owl Ventures", "website": "https://www.owlvc.com", "focus_sectors": ["EdTech", "Future of Work", "Learning"], "stage_preference": ["series-a", "series-b"], "check_size_min": 2000, "check_size_max": 30000, "geo_focus": ["United States", "Global"], "notable_portfolio": ["Duolingo", "Coursera", "Newsela"], "description": "The largest EdTech-dedicated VC firm globally.", "source": "curated"},
    {"name": "Andreessen Horowitz Cultural Leadership Fund (CLF)", "website": "https://a16z.com/clf", "focus_sectors": ["Consumer", "Entertainment", "Culture", "Creator Economy"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 10000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "a16z fund investing alongside Black cultural leaders.", "source": "curated"},
    {"name": "MaC Venture Capital", "website": "https://www.macventurecapital.com", "focus_sectors": ["Consumer", "Media", "Enterprise", "Fintech"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Multicultural VC investing in underrepresented founders.", "source": "curated"},
    {"name": "Visible Hands", "website": "https://www.visiblehands.vc", "focus_sectors": ["Technology", "SaaS", "Consumer", "Fintech"], "stage_preference": ["pre-seed"], "check_size_min": 50, "check_size_max": 250, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Early-stage fund and accelerator focused on underrepresented founders.", "source": "curated"},
    {"name": "Precursor VC (diverse)", "website": "https://precursorvc.com", "focus_sectors": ["Technology", "Consumer", "SaaS"], "stage_preference": ["pre-seed"], "check_size_min": 100, "check_size_max": 500, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Pre-seed fund backing founders before traction.", "source": "curated"},

    # Growth Stage / Private Equity crossover
    {"name": "Warburg Pincus", "website": "https://www.warburgpincus.com", "focus_sectors": ["Healthcare", "Technology", "Financial Services", "Consumer"], "stage_preference": ["growth", "buyout"], "check_size_min": 50000, "check_size_max": 2000000, "geo_focus": ["Global"], "notable_portfolio": [], "description": "Global private equity firm with long history of technology investing.", "source": "curated"},
    {"name": "KKR Tech Growth", "website": "https://www.kkr.com/our-businesses/private-equity/growth-equity", "focus_sectors": ["Technology", "SaaS", "Healthcare IT"], "stage_preference": ["growth"], "check_size_min": 50000, "check_size_max": 1000000, "geo_focus": ["Global"], "notable_portfolio": [], "description": "KKR's growth equity arm focused on software and tech.", "source": "curated"},
    {"name": "Francisco Partners", "website": "https://www.franciscopartners.com", "focus_sectors": ["Technology", "SaaS", "Healthcare IT", "Cybersecurity"], "stage_preference": ["growth"], "check_size_min": 50000, "check_size_max": 1000000, "geo_focus": ["United States", "Europe"], "notable_portfolio": [], "description": "Tech-focused buyout and growth equity firm.", "source": "curated"},
    {"name": "Vista Equity Partners", "website": "https://www.vistaequitypartners.com", "focus_sectors": ["Enterprise SaaS", "B2B Software"], "stage_preference": ["growth"], "check_size_min": 50000, "check_size_max": 5000000, "geo_focus": ["United States"], "notable_portfolio": ["Marketo", "Cvent", "Jamf", "Datto"], "description": "Largest software-focused private equity firm.", "source": "curated"},
    {"name": "Thoma Bravo", "website": "https://www.thomabravo.com", "focus_sectors": ["Enterprise Software", "Cybersecurity", "Fintech"], "stage_preference": ["growth"], "check_size_min": 100000, "check_size_max": 10000000, "geo_focus": ["United States"], "notable_portfolio": ["Proofpoint", "SolarWinds", "Sophos"], "description": "Private equity firm exclusively focused on software companies.", "source": "curated"},
    {"name": "Apax Partners", "website": "https://www.apax.com", "focus_sectors": ["Technology", "Healthcare", "Consumer", "Services"], "stage_preference": ["growth", "buyout"], "check_size_min": 100000, "check_size_max": 5000000, "geo_focus": ["Global"], "notable_portfolio": [], "description": "Global private equity firm with strong tech and healthcare portfolio.", "source": "curated"},

    # Corporate VCs
    {"name": "Qualcomm Ventures", "website": "https://www.qualcommventures.com", "focus_sectors": ["Mobile", "IoT", "5G", "AI", "Semiconductors"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 500, "check_size_max": 15000, "geo_focus": ["Global"], "notable_portfolio": [], "description": "Qualcomm's global venture arm.", "source": "curated"},
    {"name": "Samsung NEXT Ventures", "website": "https://samsungnext.com", "focus_sectors": ["AI", "IoT", "Mobile", "AR/VR", "Deep Tech"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 500, "check_size_max": 20000, "geo_focus": ["Global"], "notable_portfolio": [], "description": "Samsung's global software and services investment arm.", "source": "curated"},
    {"name": "Cisco Investments", "website": "https://ciscoventures.com", "focus_sectors": ["Networking", "Security", "AI", "IoT", "Cloud"], "stage_preference": ["series-a", "series-b"], "check_size_min": 2000, "check_size_max": 30000, "geo_focus": ["Global"], "notable_portfolio": [], "description": "Cisco's global corporate venture arm.", "source": "curated"},
    {"name": "SAP.iO Fund", "website": "https://sap.io/fund", "focus_sectors": ["Enterprise SaaS", "Supply Chain", "Finance Tech"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States", "Europe", "Asia"], "notable_portfolio": [], "description": "SAP's startup investment program and fund.", "source": "curated"},
    {"name": "ServiceNow Ventures", "website": "https://www.servicenow.com/ventures.html", "focus_sectors": ["Enterprise SaaS", "AI", "Automation", "IT Operations"], "stage_preference": ["series-a", "series-b"], "check_size_min": 2000, "check_size_max": 20000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "ServiceNow's strategic investment arm.", "source": "curated"},
    {"name": "Adobe Ventures", "website": "https://www.adobe.com/ventures.html", "focus_sectors": ["Creative Tech", "AI", "Content", "Marketing Tech"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 10000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Adobe's venture investment program.", "source": "curated"},
    {"name": "PayPal Ventures", "website": "https://paypal.com/ventures", "focus_sectors": ["Fintech", "Commerce", "Payments", "Financial Inclusion"], "stage_preference": ["series-a", "series-b"], "check_size_min": 2000, "check_size_max": 30000, "geo_focus": ["Global"], "notable_portfolio": [], "description": "PayPal's strategic investment arm.", "source": "curated"},
    {"name": "Visa Ventures", "website": "https://usa.visa.com/about-visa/newsroom/press-releases.releaseId.14836.html", "focus_sectors": ["Fintech", "Payments", "Commerce", "AI"], "stage_preference": ["series-a", "series-b"], "check_size_min": 2000, "check_size_max": 20000, "geo_focus": ["Global"], "notable_portfolio": [], "description": "Visa's strategic innovation and investment arm.", "source": "curated"},
    {"name": "MasterCard Foundry", "website": "https://developer.mastercard.com/foundry", "focus_sectors": ["Fintech", "Identity", "Security", "Commerce"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 10000, "geo_focus": ["Global"], "notable_portfolio": [], "description": "Mastercard's startup engagement and investment program.", "source": "curated"},
    {"name": "Amazon Alexa Fund", "website": "https://developer.amazon.com/en-US/alexa/alexa-startups/alexa-fund", "focus_sectors": ["Voice AI", "Conversational AI", "Smart Home", "IoT"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 500, "check_size_max": 20000, "geo_focus": ["Global"], "notable_portfolio": [], "description": "Amazon's fund for Alexa-focused startup investments.", "source": "curated"},

    # Emerging Managers / Micro-VCs
    {"name": "Catapult Ventures", "website": "https://catapult.vc", "focus_sectors": ["SaaS", "B2B", "Consumer"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 50, "check_size_max": 500, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Micro-VC fund for underrepresented founders.", "source": "curated"},
    {"name": "Narrative Fund", "website": "https://narrative.fund", "focus_sectors": ["Media", "Content", "Creator Economy", "SaaS"], "stage_preference": ["pre-seed"], "check_size_min": 25, "check_size_max": 250, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Micro-VC focused on media and creator economy.", "source": "curated"},
    {"name": "Rarebreed Ventures", "website": "https://www.rarebreedventures.com", "focus_sectors": ["Technology", "SaaS", "Consumer"], "stage_preference": ["pre-seed"], "check_size_min": 25, "check_size_max": 500, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Micro-VC backed by Next Coast Ventures.", "source": "curated"},
    {"name": "Red Sea Ventures", "website": "https://redseaventures.com", "focus_sectors": ["Media", "Sports", "Entertainment"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Sports and entertainment focused VC.", "source": "curated"},
    {"name": "FirstMark Capital", "website": "https://firstmark.com", "focus_sectors": ["Enterprise SaaS", "Consumer", "Fintech", "AI"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 10000, "geo_focus": ["United States"], "notable_portfolio": ["Pinterest", "Shopify", "DraftKings", "Airbnb"], "description": "NYC-based venture firm focused on category-defining companies.", "source": "curated"},
    {"name": "Tiger Management (tech)", "website": "https://tigermgmt.com", "focus_sectors": ["Technology", "Consumer", "Fintech", "Healthcare"], "stage_preference": ["series-b", "growth"], "check_size_min": 10000, "check_size_max": 500000, "geo_focus": ["Global"], "notable_portfolio": [], "description": "Julian Robertson's global growth-stage investor.", "source": "curated"},
    {"name": "Conviction Capital", "website": "https://conviction.com", "focus_sectors": ["AI", "Developer Tools", "Infrastructure"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 10000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "AI-native venture fund.", "source": "curated"},
    {"name": "Uncorrelated Ventures", "website": "https://uncorrelated.com", "focus_sectors": ["Infrastructure", "Security", "Open Source", "Developer Tools"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 250, "check_size_max": 3000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Technical deep-dive seed fund for infrastructure companies.", "source": "curated"},
    {"name": "Counterpart Ventures", "website": "https://counterpart.vc", "focus_sectors": ["Insurance Tech", "Risk Management", "Fintech"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Insurtech-focused seed VC.", "source": "curated"},
    {"name": "Portage Ventures", "website": "https://portage.vc", "focus_sectors": ["Fintech", "Insurance Tech", "Wealth Management"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 1000, "check_size_max": 20000, "geo_focus": ["United States", "Canada", "Europe"], "notable_portfolio": [], "description": "Fintech and insurtech focused international VC.", "source": "curated"},
    {"name": "F-Prime Capital", "website": "https://fprimecapital.com", "focus_sectors": ["Healthcare", "Biotech", "Technology", "Fintech"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 1000, "check_size_max": 20000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Healthcare and technology venture arm of Fidelity Investments.", "source": "curated"},
    {"name": "Section 32", "website": "https://section32.com", "focus_sectors": ["Deep Tech", "Biotech", "AI", "Healthcare"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 10000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Science-driven seed and Series A fund.", "source": "curated"},
    {"name": "Obvious Ventures (climate)", "website": "https://obvious.com", "focus_sectors": ["Climate", "Food Tech", "Sustainable Systems"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "World positive investing in sustainable systems.", "source": "curated"},
    {"name": "Powerhouse Ventures", "website": "https://powerhouse.fund", "focus_sectors": ["Climate Tech", "Clean Energy", "Cleantech"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 100, "check_size_max": 1000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Early-stage cleantech VC and accelerator.", "source": "curated"},
    {"name": "Avarice Ventures", "website": "https://avariceventures.com", "focus_sectors": ["Gaming", "Web3", "Consumer"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 50, "check_size_max": 500, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Gaming and web3 micro-VC fund.", "source": "curated"},
    {"name": "Velocity Capital Fintech Ventures", "website": "https://velocitycapital.vc", "focus_sectors": ["Fintech", "Payments", "Lending", "SMB Finance"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["Europe"], "notable_portfolio": [], "description": "European fintech seed and Series A VC.", "source": "curated"},
    {"name": "Founders Factory", "website": "https://foundersfactory.com", "focus_sectors": ["Consumer", "Enterprise", "Healthcare", "Fintech"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 100, "check_size_max": 1500, "geo_focus": ["Europe", "United Kingdom", "Africa"], "notable_portfolio": [], "description": "Venture studio and accelerator for early-stage startups.", "source": "curated"},
    {"name": "Antler", "website": "https://www.antler.co", "focus_sectors": ["Technology", "SaaS", "Consumer", "Fintech", "Healthcare"], "stage_preference": ["pre-seed"], "check_size_min": 100, "check_size_max": 500, "geo_focus": ["Global"], "notable_portfolio": [], "description": "Global early-stage VC building and investing from day zero.", "source": "curated"},
    {"name": "Entrepreneur First (EF)", "website": "https://www.joinef.com", "focus_sectors": ["Deep Tech", "AI", "Biotech", "Enterprise"], "stage_preference": ["pre-seed"], "check_size_min": 100, "check_size_max": 500, "geo_focus": ["Europe", "Asia", "Global"], "notable_portfolio": [], "description": "Company-builder investing in talent pre-team.", "source": "curated"},
    {"name": "Betaworks Ventures", "website": "https://betaworks.com", "focus_sectors": ["AI", "Media", "Consumer Apps", "Developer Tools"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 100, "check_size_max": 1500, "geo_focus": ["United States"], "notable_portfolio": ["Giphy", "Bit.ly", "Instapaper", "Dots"], "description": "NYC-based startup studio and seed investor.", "source": "curated"},
    {"name": "General Atlantic", "website": "https://www.generalatlantic.com", "focus_sectors": ["Technology", "Healthcare", "Consumer", "Financial Services"], "stage_preference": ["growth"], "check_size_min": 50000, "check_size_max": 2000000, "geo_focus": ["Global"], "notable_portfolio": ["Airbnb", "Alibaba", "ByteDance", "Slack"], "description": "Global growth equity firm.", "source": "curated"},
    {"name": "Summit Partners", "website": "https://www.summitpartners.com", "focus_sectors": ["Technology", "Healthcare", "Fintech", "Consumer"], "stage_preference": ["growth"], "check_size_min": 20000, "check_size_max": 500000, "geo_focus": ["United States", "Europe"], "notable_portfolio": [], "description": "Growth equity firm with $42B+ in committed capital.", "source": "curated"},
    {"name": "TA Associates", "website": "https://www.ta.com", "focus_sectors": ["Technology", "Healthcare", "Financial Services", "Consumer"], "stage_preference": ["growth"], "check_size_min": 50000, "check_size_max": 1000000, "geo_focus": ["Global"], "notable_portfolio": [], "description": "Global growth private equity firm.", "source": "curated"},
    {"name": "Providence Equity", "website": "https://www.provequity.com", "focus_sectors": ["Media", "Communications", "Education", "Technology"], "stage_preference": ["growth"], "check_size_min": 100000, "check_size_max": 5000000, "geo_focus": ["United States", "Europe"], "notable_portfolio": [], "description": "Media, communications, and technology focused private equity.", "source": "curated"},
    {"name": "Alibaba Entrepreneurs Fund", "website": "https://entrepreneursfund.alibaba.com", "focus_sectors": ["Ecommerce", "Fintech", "Consumer", "Logistics"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 500, "check_size_max": 20000, "geo_focus": ["Asia Pacific", "Hong Kong"], "notable_portfolio": [], "description": "Alibaba Group's non-profit VC fund.", "source": "curated"},
    {"name": "Tencent Investment", "website": "https://www.tencent.com/en-us/investors.html", "focus_sectors": ["Gaming", "Social", "Fintech", "AI", "Content"], "stage_preference": ["series-a", "series-b", "growth"], "check_size_min": 5000, "check_size_max": 1000000, "geo_focus": ["China", "Global"], "notable_portfolio": ["Riot Games", "Epic Games", "Snap", "Spotify"], "description": "Tencent's global strategic investment arm.", "source": "curated"},
    {"name": "Sequoia China", "website": "https://www.sequoiacap.com/china", "focus_sectors": ["Consumer", "Enterprise", "Healthcare", "Technology"], "stage_preference": ["seed", "series-a", "series-b", "growth"], "check_size_min": 500, "check_size_max": 100000, "geo_focus": ["China"], "notable_portfolio": ["Meituan", "Pinduoduo", "ByteDance"], "description": "Sequoia Capital's China operations.", "source": "curated"},
    {"name": "Hillhouse Capital", "website": "https://hillhousecap.com", "focus_sectors": ["Technology", "Healthcare", "Consumer", "Retail"], "stage_preference": ["series-b", "growth"], "check_size_min": 20000, "check_size_max": 2000000, "geo_focus": ["Asia", "China", "Global"], "notable_portfolio": ["JD.com", "Tencent", "Didi"], "description": "Major Asian technology and consumer investor.", "source": "curated"},
    {"name": "Lightspeed China Partners", "website": "https://www.lightspeedchina.com", "focus_sectors": ["Consumer", "Enterprise", "Fintech", "Healthcare"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 500, "check_size_max": 30000, "geo_focus": ["China"], "notable_portfolio": [], "description": "Lightspeed Venture Partners' China-focused fund.", "source": "curated"},
    {"name": "GIC", "website": "https://www.gic.com.sg", "focus_sectors": ["Technology", "Financial Services", "Real Estate"], "stage_preference": ["growth"], "check_size_min": 50000, "check_size_max": 5000000, "geo_focus": ["Global"], "notable_portfolio": [], "description": "Singapore's sovereign wealth fund investing globally.", "source": "curated"},
    {"name": "Temasek", "website": "https://www.temasek.com.sg", "focus_sectors": ["Technology", "Financial Services", "Telecommunications", "Life Sciences"], "stage_preference": ["growth"], "check_size_min": 100000, "check_size_max": 10000000, "geo_focus": ["Global", "Asia"], "notable_portfolio": [], "description": "Singapore state investment company with global portfolio.", "source": "curated"},
    {"name": "B Capital Group", "website": "https://www.bcapgroup.com", "focus_sectors": ["Enterprise SaaS", "Healthcare", "Fintech", "Supply Chain"], "stage_preference": ["series-a", "series-b", "growth"], "check_size_min": 5000, "check_size_max": 100000, "geo_focus": ["United States", "Asia"], "notable_portfolio": [], "description": "Global technology investor co-founded by Eduardo Saverin.", "source": "curated"},
    {"name": "Monk's Hill Ventures", "website": "https://www.monkshill.com", "focus_sectors": ["B2B SaaS", "AI", "Fintech", "Consumer"], "stage_preference": ["series-a", "series-b"], "check_size_min": 2000, "check_size_max": 20000, "geo_focus": ["Southeast Asia"], "notable_portfolio": [], "description": "Southeast Asia growth-stage VC.", "source": "curated"},

    # Dedicated AI / ML
    {"name": "AI Grant", "website": "https://aigrant.org", "focus_sectors": ["AI", "Machine Learning", "Deep Learning"], "stage_preference": ["pre-seed"], "check_size_min": 10, "check_size_max": 100, "geo_focus": ["Global"], "notable_portfolio": [], "description": "Non-dilutive AI research and startup grant fund.", "source": "curated"},
    {"name": "Radical Ventures", "website": "https://radical.vc", "focus_sectors": ["AI", "Machine Learning", "Deep Tech"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 10000, "geo_focus": ["Canada", "United States", "Global"], "notable_portfolio": [], "description": "AI-specialist VC backed by Geoffrey Hinton and other AI pioneers.", "source": "curated"},
    {"name": "Air Street Capital", "website": "https://airstreet.com", "focus_sectors": ["AI", "Machine Learning", "Biotech AI"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 100, "check_size_max": 1000, "geo_focus": ["United Kingdom", "Europe"], "notable_portfolio": [], "description": "European AI/ML pre-seed VC.", "source": "curated"},
    {"name": "Cohere for AI Ventures", "website": "https://cohere.com", "focus_sectors": ["AI", "NLP", "Enterprise AI"], "stage_preference": ["seed"], "check_size_min": 250, "check_size_max": 2500, "geo_focus": ["United States", "Canada"], "notable_portfolio": [], "description": "AI company with associated venture investment program.", "source": "curated"},

    # Biotech / Life Sciences
    {"name": "Flagship Pioneering", "website": "https://flagshippioneeringventures.com", "focus_sectors": ["Biotech", "Life Sciences", "Agriculture", "Sustainability"], "stage_preference": ["seed", "series-a"], "check_size_min": 5000, "check_size_max": 100000, "geo_focus": ["United States"], "notable_portfolio": ["Moderna", "Seres Therapeutics", "Editas Medicine"], "description": "Life sciences company-creation and venture firm that founded Moderna.", "source": "curated"},
    {"name": "Third Rock Ventures", "website": "https://www.thirdrockventures.com", "focus_sectors": ["Biotech", "Pharma", "Precision Medicine"], "stage_preference": ["seed", "series-a"], "check_size_min": 5000, "check_size_max": 50000, "geo_focus": ["United States"], "notable_portfolio": ["Blueprint Medicines", "Intellia Therapeutics"], "description": "Biotech company creator and venture firm.", "source": "curated"},
    {"name": "Foresite Capital", "website": "https://foresitecapital.com", "focus_sectors": ["Healthcare", "Biotech", "Health Tech", "Diagnostics"], "stage_preference": ["series-b", "growth"], "check_size_min": 10000, "check_size_max": 100000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Healthcare-focused crossover investment firm.", "source": "curated"},
    {"name": "EcoR1 Capital", "website": "https://www.ecor1capital.com", "focus_sectors": ["Biotech", "Oncology", "Gene Therapy"], "stage_preference": ["series-b", "growth"], "check_size_min": 10000, "check_size_max": 100000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Biotech crossover fund focused on oncology and gene therapy.", "source": "curated"},
    {"name": "Versant Ventures", "website": "https://www.versantventures.com", "focus_sectors": ["Biotech", "Medical Devices", "Diagnostics", "Drug Discovery"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 2000, "check_size_max": 50000, "geo_focus": ["United States", "Canada", "Europe"], "notable_portfolio": [], "description": "Global life sciences venture firm.", "source": "curated"},
    {"name": "Atlas Venture", "website": "https://www.atlasventure.com", "focus_sectors": ["Biotech", "Drug Discovery", "Gene Therapy"], "stage_preference": ["seed", "series-a"], "check_size_min": 2000, "check_size_max": 30000, "geo_focus": ["United States", "Europe"], "notable_portfolio": [], "description": "Company-building biotech venture firm.", "source": "curated"},
    {"name": "OrbiMed Advisors", "website": "https://www.orbimed.com", "focus_sectors": ["Biotech", "Pharma", "Medical Devices", "Healthcare"], "stage_preference": ["series-a", "series-b", "growth"], "check_size_min": 5000, "check_size_max": 100000, "geo_focus": ["Global"], "notable_portfolio": [], "description": "World's largest dedicated healthcare investment firm.", "source": "curated"},
    {"name": "RA Capital Management", "website": "https://www.racap.com", "focus_sectors": ["Biotech", "Healthcare", "Drug Discovery"], "stage_preference": ["series-a", "series-b", "growth"], "check_size_min": 5000, "check_size_max": 200000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Crossover biotech investment firm.", "source": "curated"},

    # Real Estate / PropTech
    {"name": "Fifth Wall", "website": "https://fifthwall.com", "focus_sectors": ["PropTech", "Real Estate Tech", "Construction Tech", "Climate"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 1000, "check_size_max": 30000, "geo_focus": ["United States", "Europe"], "notable_portfolio": ["Hippo", "States Title", "Opendoor"], "description": "Largest VC fund focused on the built environment and real estate tech.", "source": "curated"},
    {"name": "Metaprop", "website": "https://metaprop.vc", "focus_sectors": ["PropTech", "Smart Buildings", "Construction Tech", "Real Estate"], "stage_preference": ["pre-seed", "seed", "series-a"], "check_size_min": 250, "check_size_max": 5000, "geo_focus": ["United States", "Europe"], "notable_portfolio": [], "description": "NYC and London based PropTech focused VC.", "source": "curated"},
    {"name": "JLL Spark", "website": "https://www.jllspark.com", "focus_sectors": ["PropTech", "Smart Buildings", "Sustainability"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 500, "check_size_max": 20000, "geo_focus": ["Global"], "notable_portfolio": [], "description": "JLL's global PropTech venture fund.", "source": "curated"},

    # AgriTech / FoodTech
    {"name": "S2G Ventures", "website": "https://www.s2gventures.com", "focus_sectors": ["Food Tech", "Agtech", "Sustainable Food", "Supply Chain"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 1000, "check_size_max": 20000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Food and agriculture focused VC.", "source": "curated"},
    {"name": "Cultivian Sandbox", "website": "https://cultivian.com", "focus_sectors": ["Agtech", "Food Innovation", "Sustainability"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 10000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Agtech and food innovation venture fund.", "source": "curated"},
    {"name": "Finistere Ventures", "website": "https://www.finistereventures.com", "focus_sectors": ["Agtech", "Food Systems", "Biologics"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 10000, "geo_focus": ["United States", "Australia"], "notable_portfolio": [], "description": "Global ag innovation venture fund.", "source": "curated"},
    {"name": "Lever VC", "website": "https://www.levervc.com", "focus_sectors": ["Alternative Protein", "Food Tech", "Sustainable Food"], "stage_preference": ["seed", "series-a"], "check_size_min": 250, "check_size_max": 5000, "geo_focus": ["Global"], "notable_portfolio": [], "description": "Alternative protein and food tech focused VC.", "source": "curated"},

    # Aerospace / Defense
    {"name": "Shield Capital", "website": "https://shieldcap.com", "focus_sectors": ["Defense Tech", "Cybersecurity", "Aerospace", "AI"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 10000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "National security and defense technology focused VC.", "source": "curated"},
    {"name": "Embedded Ventures", "website": "https://embedded.vc", "focus_sectors": ["Defense Tech", "Hardware", "Robotics", "Aerospace"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 10000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Deep tech investor focused on hardware and defense.", "source": "curated"},
    {"name": "In-Q-Tel (IQT)", "website": "https://www.iqt.org", "focus_sectors": ["Cybersecurity", "AI", "Data Analytics", "Biotech"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 1000, "check_size_max": 20000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "CIA's strategic investment arm for national security tech.", "source": "curated"},
    {"name": "Starbridge Venture Capital", "website": "https://starbridgevc.com", "focus_sectors": ["Space Tech", "Aerospace", "Deep Tech"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Space technology focused seed VC.", "source": "curated"},

    # Mobility / Logistics
    {"name": "Trucks Venture Capital", "website": "https://trucks.vc", "focus_sectors": ["Mobility", "Autonomous Vehicles", "Logistics", "Supply Chain"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Seed-stage investor in supply chain and logistics tech.", "source": "curated"},
    {"name": "Autotech Ventures", "website": "https://autotechventures.com", "focus_sectors": ["Automotive", "Mobility", "Autonomous Vehicles", "EV"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 1000, "check_size_max": 15000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Automotive and mobility focused venture fund.", "source": "curated"},
    {"name": "BMW i Ventures", "website": "https://www.bmwi-ventures.com", "focus_sectors": ["Mobility", "Autonomous Driving", "EV", "Sustainability"], "stage_preference": ["series-a", "series-b"], "check_size_min": 2000, "check_size_max": 30000, "geo_focus": ["United States", "Europe"], "notable_portfolio": [], "description": "BMW Group's global venture arm.", "source": "curated"},

    # Canada
    {"name": "BDC Capital", "website": "https://www.bdc.ca/en/bdc-capital", "focus_sectors": ["Technology", "Healthcare", "Industrial", "Agriculture"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 500, "check_size_max": 20000, "geo_focus": ["Canada"], "notable_portfolio": [], "description": "Canada's development bank and VC arm.", "source": "curated"},
    {"name": "Real Ventures", "website": "https://realventures.com", "focus_sectors": ["Technology", "SaaS", "Consumer", "Fintech"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 100, "check_size_max": 2000, "geo_focus": ["Canada"], "notable_portfolio": [], "description": "Canada's most active early-stage VC fund.", "source": "curated"},
    {"name": "Georgian Partners", "website": "https://georgian.io", "focus_sectors": ["SaaS", "AI", "Privacy Tech", "Enterprise"], "stage_preference": ["series-a", "series-b"], "check_size_min": 5000, "check_size_max": 50000, "geo_focus": ["Canada", "United States"], "notable_portfolio": [], "description": "Toronto-based growth equity investor in AI-powered software.", "source": "curated"},
    {"name": "Mistral Venture Partners", "website": "https://www.mistralvp.com", "focus_sectors": ["Technology", "SaaS", "Healthcare"], "stage_preference": ["seed", "series-a"], "check_size_min": 250, "check_size_max": 3000, "geo_focus": ["Canada"], "notable_portfolio": [], "description": "Canadian seed and Series A investor.", "source": "curated"},

    # Australia / New Zealand
    {"name": "Blackbird Ventures", "website": "https://blackbird.vc", "focus_sectors": ["Technology", "SaaS", "Consumer", "Deep Tech"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 250, "check_size_max": 20000, "geo_focus": ["Australia", "New Zealand"], "notable_portfolio": ["Canva", "SafetyCulture", "Culture Amp"], "description": "Australia and New Zealand's leading venture capital firm.", "source": "curated"},
    {"name": "Airtree Ventures", "website": "https://airtree.vc", "focus_sectors": ["Technology", "SaaS", "Consumer", "Fintech"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 10000, "geo_focus": ["Australia", "New Zealand"], "notable_portfolio": [], "description": "Australia and New Zealand focused early-stage VC.", "source": "curated"},

    # General misc additional
    {"name": "Sapphire Sport", "website": "https://sapphiresport.com", "focus_sectors": ["Sports Tech", "Fan Engagement", "Media", "Wellness"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 10000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Sports technology and media venture fund.", "source": "curated"},
    {"name": "Stadium Capital", "website": "https://stadiumcap.vc", "focus_sectors": ["Sports Tech", "Gaming", "Entertainment"], "stage_preference": ["seed", "series-a"], "check_size_min": 250, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Sports and entertainment innovation seed VC.", "source": "curated"},
    {"name": "Lachy Groom", "website": "https://lachygroom.com", "focus_sectors": ["Fintech", "SaaS", "Consumer"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 50, "check_size_max": 500, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Solo GP seed fund focused on fintech and payments.", "source": "curated"},
    {"name": "Collaborative Robotics Ventures", "website": "https://crventures.vc", "focus_sectors": ["Robotics", "Automation", "Manufacturing", "AI"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 10000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Robotics and automation focused venture fund.", "source": "curated"},
    {"name": "Alumni Alliance", "website": "https://alumnialliance.vc", "focus_sectors": ["Technology", "Consumer", "Enterprise"], "stage_preference": ["seed", "series-a"], "check_size_min": 250, "check_size_max": 3000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Alumni network powered VC fund.", "source": "curated"},
    {"name": "Meritech Capital Partners", "website": "https://www.meritech.com", "focus_sectors": ["Enterprise SaaS", "Cloud", "Security", "AI"], "stage_preference": ["series-b", "series-c", "growth"], "check_size_min": 10000, "check_size_max": 100000, "geo_focus": ["United States"], "notable_portfolio": ["Facebook", "Google", "Salesforce", "Zoom"], "description": "Late-stage technology growth investor.", "source": "curated"},
    {"name": "Andreessen Horowitz FinTech", "website": "https://a16z.com/fintech", "focus_sectors": ["Fintech", "Crypto", "DeFi", "Banking as a Service"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 500, "check_size_max": 50000, "geo_focus": ["United States", "Global"], "notable_portfolio": ["Stripe", "Plaid", "Robinhood", "Coinbase"], "description": "a16z's dedicated fintech investment practice.", "source": "curated"},
    {"name": "K5 Global", "website": "https://k5global.com", "focus_sectors": ["Consumer", "Enterprise", "Media", "Entertainment"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 10000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Celebrity-backed venture fund.", "source": "curated"},
    {"name": "Science Inc.", "website": "https://science-inc.com", "focus_sectors": ["Consumer", "Marketplace", "Media", "SaaS"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 250, "check_size_max": 3000, "geo_focus": ["United States"], "notable_portfolio": ["DogVacay", "Dollar Shave Club", "eSalon"], "description": "Los Angeles based venture studio and seed fund.", "source": "curated"},
    {"name": "Defy.vc", "website": "https://defy.vc", "focus_sectors": ["Consumer", "Enterprise", "Healthcare", "Fintech"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 10000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Early-stage VC focused on non-obvious opportunities.", "source": "curated"},
    {"name": "Phoenix Court Group", "website": "https://phoenixcourt.com", "focus_sectors": ["Technology", "Consumer", "Healthcare"], "stage_preference": ["seed", "series-a"], "check_size_min": 250, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Multi-stage technology investor.", "source": "curated"},
    {"name": "Vertex Ventures", "website": "https://vertexventures.com", "focus_sectors": ["Technology", "Healthcare", "Consumer", "Fintech"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 500, "check_size_max": 20000, "geo_focus": ["Singapore", "Southeast Asia", "Global"], "notable_portfolio": ["Grab", "Patsnap"], "description": "Singapore-based global VC network.", "source": "curated"},
    {"name": "Wavemaker Partners", "website": "https://wavemaker.vc", "focus_sectors": ["B2B SaaS", "Deep Tech", "Supply Chain", "Fintech"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["Southeast Asia", "United States"], "notable_portfolio": [], "description": "Bi-coastal B2B tech seed fund with Southeast Asia focus.", "source": "curated"},
    {"name": "Gunderson Seed Fund", "website": "https://gunderson.com/seed", "focus_sectors": ["Technology", "SaaS", "Consumer"], "stage_preference": ["pre-seed"], "check_size_min": 25, "check_size_max": 250, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Legal industry backed micro-seed fund.", "source": "curated"},
    {"name": "Omers Ventures", "website": "https://www.omersventures.com", "focus_sectors": ["Technology", "SaaS", "Fintech", "Healthcare"], "stage_preference": ["series-a", "series-b"], "check_size_min": 5000, "check_size_max": 50000, "geo_focus": ["Canada", "United States", "Europe"], "notable_portfolio": ["Shopify", "Wave", "Hootsuite"], "description": "OMERS pension fund's venture capital arm.", "source": "curated"},
    {"name": "McRock Capital", "website": "https://mcrockcapital.com", "focus_sectors": ["Industrial IoT", "Smart Manufacturing", "Energy", "Agriculture"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 10000, "geo_focus": ["Canada", "United States"], "notable_portfolio": [], "description": "Industrial IoT focused venture fund.", "source": "curated"},
    {"name": "Radical VC", "website": "https://radical.vc", "focus_sectors": ["AI", "Deep Learning", "Enterprise AI"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 10000, "geo_focus": ["Canada", "United States"], "notable_portfolio": [], "description": "AI-specialist fund backed by AI research community.", "source": "curated"},
]


def main():
    print(f"Batch 2: Loading {len(BATCH2)} additional curated VC records...")
    seen = set()
    deduped = []
    for r in BATCH2:
        n = r["name"].lower().strip()
        if n not in seen:
            seen.add(n)
            deduped.append(r)
    print(f"After dedup: {len(deduped)} unique in batch")

    total = 0
    for i in range(0, len(deduped), 50):
        batch = deduped[i:i+50]
        loaded = upsert_vcs(batch)
        total += loaded
        print(f"  Batch {i//50+1}: +{loaded}")

    print(f"\nBatch 2 done: {total} records loaded")

    # Validate total
    url = f"{SUPABASE_URL}/rest/v1/vcs?select=count"
    headers = {
        "apikey": SERVICE_ROLE_KEY,
        "Authorization": f"Bearer {SERVICE_ROLE_KEY}",
        "Prefer": "count=exact",
    }
    resp = requests.head(url, headers=headers, timeout=10)
    print(f"Total vcs count: {resp.headers.get('content-range', 'unknown')}")


if __name__ == "__main__":
    main()
