#!/usr/bin/env python3
"""VC Seed Batch 3 — final top-up to reach 500+"""
import os, requests

SUPABASE_URL = os.environ.get("SUPABASE_URL", "https://tnloaqibvtekphwjehwc.supabase.co")
SERVICE_ROLE_KEY = os.environ.get("SUPABASE_SERVICE_ROLE_KEY", "")

def upsert_vcs(records):
    if not records: return 0
    url = f"{SUPABASE_URL}/rest/v1/vcs?on_conflict=name"
    h = {"apikey": SERVICE_ROLE_KEY, "Authorization": f"Bearer {SERVICE_ROLE_KEY}",
         "Content-Type": "application/json", "Prefer": "resolution=merge-duplicates,return=minimal"}
    r = requests.post(url, headers=h, json=records, timeout=30)
    if r.status_code not in (200, 201):
        print(f"  [WARN] {r.status_code}: {r.text[:200]}")
        return 0
    return len(records)

BATCH3 = [
    {"name": "Lightbank", "website": "https://www.lightbank.com", "focus_sectors": ["Enterprise SaaS", "Fintech", "Consumer"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["Midwest", "Chicago"], "notable_portfolio": [], "description": "Chicago-based early-stage technology VC.", "source": "curated"},
    {"name": "Decibel Partners", "website": "https://decibel.vc", "focus_sectors": ["Infrastructure", "Security", "SaaS", "AI"], "stage_preference": ["seed", "series-a"], "check_size_min": 1000, "check_size_max": 10000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Enterprise and infrastructure focused seed VC.", "source": "curated"},
    {"name": "Montage Ventures", "website": "https://montageventures.com", "focus_sectors": ["Consumer", "FinTech", "Healthcare", "Enterprise"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Silicon Valley based seed and Series A investor.", "source": "curated"},
    {"name": "Acceleprise", "website": "https://acceleprise.vc", "focus_sectors": ["B2B SaaS", "Enterprise"], "stage_preference": ["pre-seed"], "check_size_min": 50, "check_size_max": 200, "geo_focus": ["United States"], "notable_portfolio": [], "description": "B2B SaaS accelerator and pre-seed fund.", "source": "curated"},
    {"name": "Arena Ventures", "website": "https://arenavc.com", "focus_sectors": ["Sports", "Health", "Wellness", "Consumer"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Sports, health, and wellness focused venture fund.", "source": "curated"},
    {"name": "Vamos Ventures", "website": "https://vamos.ventures", "focus_sectors": ["Consumer", "Fintech", "Healthcare"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States", "Latin America"], "notable_portfolio": [], "description": "Latinx-focused VC fund.", "source": "curated"},
    {"name": "Cowboy Ventures", "website": "https://cowboy.vc", "focus_sectors": ["Consumer", "Enterprise SaaS", "Healthcare"], "stage_preference": ["seed"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Seed-stage generalist VC led by Aileen Lee.", "source": "curated"},
    {"name": "Aspect Ventures", "website": "https://aspectventures.com", "focus_sectors": ["Consumer", "Enterprise", "AI"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Diverse founders focused venture fund.", "source": "curated"},
    {"name": "Background Capital", "website": "https://background.capital", "focus_sectors": ["Developer Tools", "Infrastructure", "SaaS"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 100, "check_size_max": 1000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Infrastructure and developer tools seed fund.", "source": "curated"},
    {"name": "Basecamp Fund", "website": "https://basecampfund.com", "focus_sectors": ["Consumer", "SaaS", "Marketplace"], "stage_preference": ["pre-seed"], "check_size_min": 25, "check_size_max": 250, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Pre-seed micro-VC.", "source": "curated"},
    {"name": "Clearbit Capital", "website": "https://clearbitcapital.com", "focus_sectors": ["B2B SaaS", "Data", "AI"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Data-driven B2B SaaS investor.", "source": "curated"},
    {"name": "Courtside Ventures", "website": "https://courtsidevc.com", "focus_sectors": ["Sports", "Media", "Entertainment", "Consumer"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Sports media and entertainment venture fund.", "source": "curated"},
    {"name": "Day One Ventures", "website": "https://dayoneventures.com", "focus_sectors": ["Consumer", "SaaS", "Social Impact"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 100, "check_size_max": 1000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Pre-seed and seed fund backed by Maren Bannon.", "source": "curated"},
    {"name": "Dundee Venture Capital", "website": "https://dundeevc.com", "focus_sectors": ["SaaS", "Enterprise", "Consumer"], "stage_preference": ["seed"], "check_size_min": 250, "check_size_max": 3000, "geo_focus": ["Midwest", "United States"], "notable_portfolio": [], "description": "Omaha-based seed fund for the heartland.", "source": "curated"},
    {"name": "Everywhere Ventures II", "website": "https://everywhere.vc", "focus_sectors": ["Consumer", "B2B SaaS", "Fintech"], "stage_preference": ["pre-seed"], "check_size_min": 25, "check_size_max": 250, "geo_focus": ["Global"], "notable_portfolio": [], "description": "Globally dispersed micro-VC.", "source": "curated"},
    {"name": "Founder Collective", "website": "https://foundercollective.com", "focus_sectors": ["Consumer", "Enterprise", "Fintech"], "stage_preference": ["seed"], "check_size_min": 250, "check_size_max": 3000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Founder-run seed fund backing early-stage companies.", "source": "curated"},
    {"name": "Gaingels", "website": "https://gaingels.com", "focus_sectors": ["Technology", "Consumer", "SaaS", "Fintech"], "stage_preference": ["seed", "series-a"], "check_size_min": 50, "check_size_max": 1000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "LGBTQ+ aligned venture community and investor.", "source": "curated"},
    {"name": "Good Friends", "website": "https://goodfriends.com", "focus_sectors": ["Consumer", "Media", "Entertainment"], "stage_preference": ["seed"], "check_size_min": 250, "check_size_max": 3000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Consumer brand and media focused seed VC.", "source": "curated"},
    {"name": "Great Oaks Venture Capital", "website": "https://www.greatoaksvc.com", "focus_sectors": ["Technology", "Consumer", "Fintech"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 25, "check_size_max": 250, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Micro-VC writing $25K-$250K checks.", "source": "curated"},
    {"name": "Ground Up Ventures", "website": "https://groundup.vc", "focus_sectors": ["SaaS", "Consumer", "Marketplace"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 100, "check_size_max": 1000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Seed fund backing founders building category-defining companies.", "source": "curated"},
    {"name": "HBCU VC", "website": "https://www.hbcuvc.com", "focus_sectors": ["Technology", "Consumer", "Social Impact"], "stage_preference": ["pre-seed"], "check_size_min": 10, "check_size_max": 100, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Supporting HBCU students enter venture capital.", "source": "curated"},
    {"name": "Intact Ventures", "website": "https://intactventures.com", "focus_sectors": ["InsurTech", "Climate", "Fintech"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 10000, "geo_focus": ["Canada", "United States"], "notable_portfolio": [], "description": "Intact Insurance's strategic venture arm.", "source": "curated"},
    {"name": "Interplay Ventures", "website": "https://interplay.vc", "focus_sectors": ["Fintech", "Real Estate", "Insurance", "Data"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Fintech and real estate tech focused venture studio.", "source": "curated"},
    {"name": "JME Ventures", "website": "https://jme.vc", "focus_sectors": ["SaaS", "Fintech", "Marketplace", "Consumer"], "stage_preference": ["seed", "series-a"], "check_size_min": 250, "check_size_max": 3000, "geo_focus": ["Europe", "Spain"], "notable_portfolio": [], "description": "Madrid-based seed and Series A investor.", "source": "curated"},
    {"name": "Join Capital", "website": "https://www.join.capital", "focus_sectors": ["B2B SaaS", "Enterprise", "Developer Tools"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 7000, "geo_focus": ["Europe", "Germany"], "notable_portfolio": [], "description": "Berlin-based B2B SaaS seed investor.", "source": "curated"},
    {"name": "Kindred Capital", "website": "https://www.kindredcapital.vc", "focus_sectors": ["Consumer", "Enterprise SaaS", "Deep Tech", "Health"], "stage_preference": ["seed"], "check_size_min": 250, "check_size_max": 3000, "geo_focus": ["Europe", "United Kingdom"], "notable_portfolio": [], "description": "European seed fund with unique equity sharing model.", "source": "curated"},
    {"name": "La Famiglia", "website": "https://www.la-famiglia.vc", "focus_sectors": ["Enterprise SaaS", "B2B", "Future of Work"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["Europe"], "notable_portfolio": [], "description": "European VC backed by industry leaders.", "source": "curated"},
    {"name": "Lean Ventures", "website": "https://leanventures.com", "focus_sectors": ["B2B SaaS", "Fintech", "Deep Tech"], "stage_preference": ["seed"], "check_size_min": 250, "check_size_max": 3000, "geo_focus": ["Europe", "Spain"], "notable_portfolio": [], "description": "Spanish tech seed fund.", "source": "curated"},
    {"name": "Left Lane Capital", "website": "https://leftlanecap.com", "focus_sectors": ["Consumer Internet", "Marketplace", "SaaS", "Fintech"], "stage_preference": ["series-a", "series-b"], "check_size_min": 5000, "check_size_max": 75000, "geo_focus": ["United States", "Europe"], "notable_portfolio": [], "description": "Growth-stage internet company investor.", "source": "curated"},
    {"name": "Longitude Capital", "website": "https://longitudecapital.com", "focus_sectors": ["Life Sciences", "Healthcare", "Biotech"], "stage_preference": ["series-a", "series-b"], "check_size_min": 5000, "check_size_max": 50000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Life sciences and healthcare crossover fund.", "source": "curated"},
    {"name": "Lupa Systems", "website": "https://lupasystems.com", "focus_sectors": ["Media", "Sports", "Consumer", "Technology"], "stage_preference": ["series-a", "series-b"], "check_size_min": 5000, "check_size_max": 100000, "geo_focus": ["Global"], "notable_portfolio": [], "description": "James Murdoch's investment vehicle.", "source": "curated"},
    {"name": "March Capital", "website": "https://marchcp.com", "focus_sectors": ["AI", "Cybersecurity", "Cloud", "Enterprise"], "stage_preference": ["series-a", "series-b"], "check_size_min": 5000, "check_size_max": 30000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "AI and cybersecurity focused growth-stage VC.", "source": "curated"},
    {"name": "M25 Group", "website": "https://m25vc.com", "focus_sectors": ["SaaS", "B2B", "Fintech", "Healthcare"], "stage_preference": ["seed", "series-a"], "check_size_min": 250, "check_size_max": 3000, "geo_focus": ["Midwest", "United States"], "notable_portfolio": [], "description": "Midwest-focused early-stage VC fund.", "source": "curated"},
    {"name": "Mindset Ventures", "website": "https://mindsetventures.com", "focus_sectors": ["B2B SaaS", "Deep Tech", "AI", "Health Tech"], "stage_preference": ["seed", "series-a"], "check_size_min": 250, "check_size_max": 3000, "geo_focus": ["Brazil", "United States", "Israel"], "notable_portfolio": [], "description": "Brazilian VC connecting Israel and the Americas.", "source": "curated"},
    {"name": "Morado Ventures", "website": "https://morado.vc", "focus_sectors": ["Consumer", "Fintech", "Future of Work"], "stage_preference": ["seed"], "check_size_min": 250, "check_size_max": 3000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Seed fund backing Latinx founders.", "source": "curated"},
    {"name": "Next Ventures", "website": "https://next.vc", "focus_sectors": ["Enterprise SaaS", "Deep Tech", "Infrastructure"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Enterprise and deep tech seed fund.", "source": "curated"},
    {"name": "NextView Ventures", "website": "https://nextviewventures.com", "focus_sectors": ["Consumer", "Enterprise", "Fintech"], "stage_preference": ["seed"], "check_size_min": 250, "check_size_max": 3000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Everyday economy focused seed fund.", "source": "curated"},
    {"name": "Nomad Capital", "website": "https://nomadcap.vc", "focus_sectors": ["B2B SaaS", "Infrastructure", "Fintech"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 100, "check_size_max": 1000, "geo_focus": ["Global"], "notable_portfolio": [], "description": "Location-independent seed fund.", "source": "curated"},
    {"name": "Noosphere Ventures", "website": "https://noosphereventures.com", "focus_sectors": ["Deep Tech", "Space", "Energy", "AI"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 10000, "geo_focus": ["United States", "Global"], "notable_portfolio": [], "description": "Mission-driven deep tech VC fund.", "source": "curated"},
    {"name": "Oddball Ventures", "website": "https://oddball.vc", "focus_sectors": ["Consumer", "Media", "Creator Economy"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 50, "check_size_max": 500, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Creator economy and media focused micro-VC.", "source": "curated"},
    {"name": "Pascal Venture Partners", "website": "https://pascal.vc", "focus_sectors": ["Enterprise SaaS", "Developer Tools", "Infrastructure"], "stage_preference": ["seed"], "check_size_min": 250, "check_size_max": 3000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Technical enterprise seed fund.", "source": "curated"},
    {"name": "Pear Pioneer", "website": "https://pear.vc/pioneer", "focus_sectors": ["Deep Tech", "Bio", "Enterprise"], "stage_preference": ["pre-seed"], "check_size_min": 50, "check_size_max": 500, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Pear VC's university innovation program.", "source": "curated"},
    {"name": "Pipeline Angels", "website": "https://pipelineangels.com", "focus_sectors": ["Social Enterprise", "Technology", "Consumer"], "stage_preference": ["pre-seed"], "check_size_min": 25, "check_size_max": 250, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Angel fund supporting women and nonbinary social entrepreneurs.", "source": "curated"},
    {"name": "Playfair Ventures", "website": "https://playfairventures.com", "focus_sectors": ["Gaming", "Consumer", "Entertainment"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Gaming-focused early-stage venture fund.", "source": "curated"},
    {"name": "Portland Seed Fund", "website": "https://portlandsedfund.com", "focus_sectors": ["Technology", "SaaS", "Consumer"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 25, "check_size_max": 500, "geo_focus": ["Pacific Northwest", "United States"], "notable_portfolio": [], "description": "Portland Oregon seed fund.", "source": "curated"},
    {"name": "Potluck Ventures", "website": "https://potluck.vc", "focus_sectors": ["Consumer", "Fintech", "SaaS"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 100, "check_size_max": 1000, "geo_focus": ["United States", "Asia Pacific"], "notable_portfolio": [], "description": "Diversity-focused seed fund.", "source": "curated"},
    {"name": "Proeza Ventures", "website": "https://proeza.vc", "focus_sectors": ["Mobility", "Manufacturing", "Industrial Tech"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["Mexico", "Latin America"], "notable_portfolio": [], "description": "Mexico-based mobility and industrial tech VC.", "source": "curated"},
    {"name": "Prosus Ventures", "website": "https://www.prosus.com/ventures", "focus_sectors": ["Edtech", "Fintech", "Food Delivery", "Healthcare"], "stage_preference": ["series-a", "series-b"], "check_size_min": 5000, "check_size_max": 100000, "geo_focus": ["Global", "Emerging Markets"], "notable_portfolio": ["Swiggy", "BYJU's", "Meituan"], "description": "Naspers/Prosus global technology venture fund.", "source": "curated"},
    {"name": "Relay Ventures", "website": "https://relayventures.com", "focus_sectors": ["Mobile", "SaaS", "Enterprise"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["Canada"], "notable_portfolio": [], "description": "Canada-focused mobile and enterprise tech seed fund.", "source": "curated"},
    {"name": "Root Ventures", "website": "https://root.vc", "focus_sectors": ["Hardware", "Developer Tools", "Manufacturing", "Robotics"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 250, "check_size_max": 3000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Seed fund for hardware and technical founders.", "source": "curated"},
    {"name": "RTF (Round Table Food) Capital", "website": "https://rtfcap.com", "focus_sectors": ["Food Tech", "Consumer Brands", "Retail"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Food, beverage and consumer brand focused venture.", "source": "curated"},
    {"name": "Sapphire Ventures Growth", "website": "https://sapphireventures.com/growth", "focus_sectors": ["SaaS", "Enterprise", "Cybersecurity", "AI"], "stage_preference": ["growth"], "check_size_min": 20000, "check_size_max": 150000, "geo_focus": ["United States", "Europe"], "notable_portfolio": [], "description": "Sapphire Ventures growth equity practice.", "source": "curated"},
    {"name": "Sievert Larsen & Associates", "website": "https://sievertlarsen.com", "focus_sectors": ["Industrial", "Manufacturing", "Energy"], "stage_preference": ["seed", "series-a"], "check_size_min": 250, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Industrial innovation venture fund.", "source": "curated"},
    {"name": "Sofinnova Partners", "website": "https://www.sofinnova.vc", "focus_sectors": ["Biotech", "Healthcare", "Life Sciences"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 2000, "check_size_max": 30000, "geo_focus": ["Europe", "United States"], "notable_portfolio": [], "description": "Paris-based life sciences venture firm.", "source": "curated"},
    {"name": "Steelpoint Capital", "website": "https://steelpointcap.com", "focus_sectors": ["Defense", "Homeland Security", "Cybersecurity"], "stage_preference": ["series-a", "series-b"], "check_size_min": 5000, "check_size_max": 50000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Defense and homeland security focused PE/VC.", "source": "curated"},
    {"name": "StepChange Ventures", "website": "https://stepchange.vc", "focus_sectors": ["Consumer Health", "Wellness", "Insurance"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Consumer health and wellness venture investor.", "source": "curated"},
    {"name": "Story Ventures", "website": "https://story.vc", "focus_sectors": ["Media", "Consumer", "Creator Economy"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 100, "check_size_max": 1000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Media and creator economy micro-VC.", "source": "curated"},
    {"name": "Stripes", "website": "https://stripesgroup.com", "focus_sectors": ["Consumer", "SaaS", "Marketplace"], "stage_preference": ["series-b", "series-c"], "check_size_min": 10000, "check_size_max": 100000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Growth equity firm focused on founder-owned businesses.", "source": "curated"},
    {"name": "Structura Ventures", "website": "https://structura.vc", "focus_sectors": ["Construction Tech", "PropTech", "Infrastructure"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Construction technology focused VC.", "source": "curated"},
    {"name": "SV Tech Ventures", "website": "https://svtechventures.com", "focus_sectors": ["AI", "Enterprise SaaS", "Deep Tech"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States", "South Korea"], "notable_portfolio": [], "description": "Korean-American bridge venture fund.", "source": "curated"},
    {"name": "Thesis Ventures", "website": "https://thesis.vc", "focus_sectors": ["Consumer", "Healthcare", "Climate"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 100, "check_size_max": 1000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Thesis-driven pre-seed and seed fund.", "source": "curated"},
    {"name": "TiE Angels", "website": "https://www.tie.org/tie-angels", "focus_sectors": ["Technology", "Consumer", "Fintech"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 50, "check_size_max": 500, "geo_focus": ["United States", "India", "Global"], "notable_portfolio": [], "description": "TiE network's angel investment program.", "source": "curated"},
    {"name": "Trousdale Ventures", "website": "https://trousdale.vc", "focus_sectors": ["Consumer", "Media", "Entertainment"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["Los Angeles", "United States"], "notable_portfolio": [], "description": "LA-focused consumer media and entertainment VC.", "source": "curated"},
    {"name": "Tx Tech Ventures", "website": "https://txtechventures.com", "focus_sectors": ["Technology", "SaaS", "Consumer"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 100, "check_size_max": 1000, "geo_focus": ["Texas", "United States"], "notable_portfolio": [], "description": "Texas-focused tech seed fund.", "source": "curated"},
    {"name": "UpHonest Capital", "website": "https://uphonest.com", "focus_sectors": ["B2B SaaS", "AI", "Fintech"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States", "China"], "notable_portfolio": [], "description": "US-China cross-border venture fund.", "source": "curated"},
    {"name": "Varana Capital", "website": "https://varanacapital.com", "focus_sectors": ["Fintech", "Insurance Tech", "Real Estate Tech"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Financial services innovation VC.", "source": "curated"},
    {"name": "Vestech Partners", "website": "https://vestechpartners.com", "focus_sectors": ["Healthcare", "Life Sciences", "Biotech"], "stage_preference": ["series-a", "series-b"], "check_size_min": 2000, "check_size_max": 20000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Healthcare and life sciences growth investor.", "source": "curated"},
    {"name": "Vinland Capital", "website": "https://vinlandcap.com", "focus_sectors": ["Consumer", "Retail", "E-commerce"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Consumer and retail focused VC.", "source": "curated"},
    {"name": "Vista Venture Partners", "website": "https://vistavp.com", "focus_sectors": ["Healthcare", "SaaS", "Life Sciences"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Healthcare and SaaS focused seed fund.", "source": "curated"},
    {"name": "Walden International", "website": "https://walden.com", "focus_sectors": ["Semiconductors", "Deep Tech", "AI", "IoT"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 1000, "check_size_max": 20000, "geo_focus": ["United States", "Asia"], "notable_portfolio": [], "description": "Semiconductor and deep tech VC firm.", "source": "curated"},
    {"name": "WestTech Ventures", "website": "https://westtechventures.com", "focus_sectors": ["Technology", "SaaS", "Consumer"], "stage_preference": ["seed"], "check_size_min": 250, "check_size_max": 2500, "geo_focus": ["Mountain West", "United States"], "notable_portfolio": [], "description": "Mountain West tech ecosystem seed fund.", "source": "curated"},
    {"name": "Winged Keel Partners", "website": "https://wingedkeel.com", "focus_sectors": ["Fintech", "Insurance", "Financial Services"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Fintech and financial services focused VC.", "source": "curated"},
    {"name": "Wiredelta", "website": "https://wiredelta.vc", "focus_sectors": ["B2B SaaS", "Fintech", "Consumer"], "stage_preference": ["seed"], "check_size_min": 100, "check_size_max": 1000, "geo_focus": ["Scandinavia", "Europe"], "notable_portfolio": [], "description": "Nordic seed fund.", "source": "curated"},
    {"name": "Ybrant Ventures", "website": "https://ybrantventures.com", "focus_sectors": ["Consumer", "Digital Media", "AdTech"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["India", "Middle East"], "notable_portfolio": [], "description": "India and Middle East focused digital media VC.", "source": "curated"},
    {"name": "Zetta Venture Partners", "website": "https://zetta.vc", "focus_sectors": ["AI", "Machine Learning", "Enterprise SaaS"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 10000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "AI-focused seed and Series A fund.", "source": "curated"},
    {"name": "Zero Prime Ventures", "website": "https://zeroprime.vc", "focus_sectors": ["AI", "Developer Tools", "Infrastructure"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 100, "check_size_max": 1000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "AI infrastructure and developer tools micro-VC.", "source": "curated"},
    {"name": "Zigg Capital", "website": "https://zigg.com", "focus_sectors": ["PropTech", "Construction Tech", "Real Estate"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "PropTech dedicated early-stage VC.", "source": "curated"},
    {"name": "Andreessen Horowitz Infrastructure", "website": "https://a16z.com/infrastructure", "focus_sectors": ["Infrastructure", "Cloud", "Open Source", "Developer Tools"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 500, "check_size_max": 50000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "a16z's infrastructure and cloud investment practice.", "source": "curated"},
    {"name": "Craft Ventures", "website": "https://craftventures.com", "focus_sectors": ["SaaS", "Consumer", "Fintech", "Crypto"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 10000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "David Sacks and Bill Lee's seed and Series A fund.", "source": "curated"},
    {"name": "Kindred Ventures", "website": "https://kindred.vc", "focus_sectors": ["Consumer", "SaaS", "Crypto", "Marketplace"], "stage_preference": ["seed"], "check_size_min": 250, "check_size_max": 3000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Seed-stage generalist VC.", "source": "curated"},
    {"name": "Palm Drive Capital", "website": "https://palmdrive.vc", "focus_sectors": ["Enterprise SaaS", "AI", "Fintech"], "stage_preference": ["seed"], "check_size_min": 100, "check_size_max": 1000, "geo_focus": ["United States", "China"], "notable_portfolio": [], "description": "Sino-American venture bridge fund.", "source": "curated"},
    {"name": "Shrug Capital", "website": "https://shrug.vc", "focus_sectors": ["Consumer", "Developer Tools", "SaaS"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 50, "check_size_max": 500, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Personality-driven micro-VC fund.", "source": "curated"},
    {"name": "Caffeinated Capital", "website": "https://caffeinatedcapital.com", "focus_sectors": ["Consumer", "SaaS", "Crypto", "AI"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "San Francisco based seed fund.", "source": "curated"},
    {"name": "Abstract Ventures II", "website": "https://abstract.vc", "focus_sectors": ["Developer Tools", "Enterprise", "AI"], "stage_preference": ["seed"], "check_size_min": 250, "check_size_max": 2500, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Technical seed fund for B2B infrastructure.", "source": "curated"},
    {"name": "Charge Ventures", "website": "https://charge.vc", "focus_sectors": ["Consumer", "Fintech", "SaaS", "Marketplace"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 100, "check_size_max": 1000, "geo_focus": ["New York", "United States"], "notable_portfolio": [], "description": "NYC-based early-stage investor.", "source": "curated"},
    {"name": "Correlation Ventures", "website": "https://correlationvc.com", "focus_sectors": ["Technology", "Healthcare", "SaaS"], "stage_preference": ["seed", "series-a"], "check_size_min": 100, "check_size_max": 2000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Data-driven VC co-investor that never leads rounds.", "source": "curated"},
    {"name": "Dorm Room Fund", "website": "https://dormroomfund.com", "focus_sectors": ["Technology", "Consumer", "SaaS"], "stage_preference": ["pre-seed"], "check_size_min": 20, "check_size_max": 50, "geo_focus": ["United States"], "notable_portfolio": [], "description": "First Round Capital's student-run venture fund.", "source": "curated"},
    {"name": "Pear VC Fellows", "website": "https://pear.vc/fellows", "focus_sectors": ["Technology", "SaaS", "Consumer"], "stage_preference": ["pre-seed"], "check_size_min": 50, "check_size_max": 250, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Pear VC's student and early-career program.", "source": "curated"},
    {"name": "Maverick Capital Ventures", "website": "https://maverickcap.com/ventures", "focus_sectors": ["Technology", "Consumer", "Healthcare", "Fintech"], "stage_preference": ["growth"], "check_size_min": 10000, "check_size_max": 100000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Maverick Capital's venture and growth equity arm.", "source": "curated"},
    {"name": "Third Point Ventures", "website": "https://thirdpointventures.com", "focus_sectors": ["Technology", "Fintech", "Healthcare", "Consumer"], "stage_preference": ["growth"], "check_size_min": 20000, "check_size_max": 200000, "geo_focus": ["Global"], "notable_portfolio": [], "description": "Dan Loeb's technology growth investment arm.", "source": "curated"},
    {"name": "Valor Equity Partners", "website": "https://valorep.com", "focus_sectors": ["Deep Tech", "Manufacturing", "Robotics", "Energy"], "stage_preference": ["series-a", "series-b", "growth"], "check_size_min": 5000, "check_size_max": 100000, "geo_focus": ["United States"], "notable_portfolio": ["SpaceX", "Tesla (early)"], "description": "Growth equity firm focused on industrial transformation.", "source": "curated"},
    {"name": "WS Investments", "website": "https://wsinvestments.com", "focus_sectors": ["Consumer", "Technology", "Healthcare"], "stage_preference": ["seed", "series-a"], "check_size_min": 250, "check_size_max": 3000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Family office and venture fund.", "source": "curated"},
    {"name": "TechNexus", "website": "https://technexus.com", "focus_sectors": ["Enterprise", "Industrial", "B2B"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["Midwest", "United States"], "notable_portfolio": [], "description": "Enterprise-focused VC collaborative.", "source": "curated"},
    {"name": "Stormbreaker VC", "website": "https://stormbreaker.vc", "focus_sectors": ["Consumer", "SaaS", "Health"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 100, "check_size_max": 1000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Early-stage generalist seed fund.", "source": "curated"},
    {"name": "StartX Fund", "website": "https://startx.com", "focus_sectors": ["Technology", "Healthcare", "Consumer", "Deep Tech"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 25, "check_size_max": 250, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Stanford alumni-affiliated startup accelerator and fund.", "source": "curated"},
    {"name": "Recharge Capital", "website": "https://recharge.capital", "focus_sectors": ["Consumer", "Health", "Wellness", "Fitness"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Health, wellness, and fitness venture fund.", "source": "curated"},
    {"name": "Project 11 Ventures", "website": "https://project11.com", "focus_sectors": ["AI", "ML", "Data Science"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 250, "check_size_max": 2000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "AI-first seed fund.", "source": "curated"},
    {"name": "Plexo Capital", "website": "https://plexocap.com", "focus_sectors": ["Consumer", "Enterprise", "Fintech", "Healthcare"], "stage_preference": ["seed"], "check_size_min": 250, "check_size_max": 3000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "LP-focused diverse founders fund.", "source": "curated"},
    {"name": "Piva Capital", "website": "https://piva.com", "focus_sectors": ["Energy", "Industrial Tech", "Climate", "Advanced Manufacturing"], "stage_preference": ["series-a", "series-b"], "check_size_min": 5000, "check_size_max": 50000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Industrial innovation and energy transition investor.", "source": "curated"},
    {"name": "Moxxie Ventures", "website": "https://moxxie.vc", "focus_sectors": ["Consumer", "Enterprise", "Healthcare"], "stage_preference": ["seed"], "check_size_min": 250, "check_size_max": 2000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Values-driven seed fund.", "source": "curated"},
    {"name": "Loyal VC", "website": "https://loyal.vc", "focus_sectors": ["Technology", "SaaS", "Consumer"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 50, "check_size_max": 500, "geo_focus": ["Global"], "notable_portfolio": [], "description": "Revenue-share and equity venture fund.", "source": "curated"},
    {"name": "Knollwood Investment Advisory", "website": "https://knollwoodinvest.com", "focus_sectors": ["Technology", "Healthcare", "Consumer"], "stage_preference": ["seed", "series-a"], "check_size_min": 250, "check_size_max": 3000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Early-stage technology investor.", "source": "curated"},
    {"name": "K9 Ventures", "website": "https://k9ventures.com", "focus_sectors": ["Developer Tools", "SaaS", "Enterprise", "AI"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 100, "check_size_max": 500, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Solo GP technical seed fund.", "source": "curated"},
    {"name": "Impact Engine", "website": "https://theimpactengine.com", "focus_sectors": ["Impact", "Healthcare", "Education", "Financial Inclusion"], "stage_preference": ["seed", "series-a"], "check_size_min": 250, "check_size_max": 3000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Double bottom line impact investing fund.", "source": "curated"},
    {"name": "Hummingbird Ventures", "website": "https://hummingbird.vc", "focus_sectors": ["SaaS", "Marketplace", "Consumer", "Fintech"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["Europe", "Global"], "notable_portfolio": [], "description": "Global emerging markets seed and Series A fund.", "source": "curated"},
    {"name": "HOF Capital", "website": "https://hofcapital.com", "focus_sectors": ["Technology", "Consumer", "SaaS", "Fintech"], "stage_preference": ["seed", "series-a"], "check_size_min": 250, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Hall of Famers' athlete-backed VC fund.", "source": "curated"},
    {"name": "High Alpha", "website": "https://highalpha.com", "focus_sectors": ["Enterprise SaaS", "B2B"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["Midwest", "United States"], "notable_portfolio": [], "description": "Indianapolis-based venture studio and SaaS investor.", "source": "curated"},
    {"name": "Global Founders Capital", "website": "https://globalfounderscapital.com", "focus_sectors": ["Consumer", "Marketplace", "Fintech", "SaaS"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 10000, "geo_focus": ["Global"], "notable_portfolio": [], "description": "Stage-agnostic global VC backed by Rocket Internet founders.", "source": "curated"},
    {"name": "Fuel Capital", "website": "https://fuelcapital.com", "focus_sectors": ["Consumer", "SaaS", "Marketplace"], "stage_preference": ["seed"], "check_size_min": 250, "check_size_max": 3000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Seed-stage venture fund.", "source": "curated"},
    {"name": "Female Founders Fund", "website": "https://femalefoundersfund.com", "focus_sectors": ["Consumer", "Healthcare", "SaaS", "Fintech"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 100, "check_size_max": 1000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Venture fund focused exclusively on female founders.", "source": "curated"},
    {"name": "F7 Ventures", "website": "https://f7ventures.com", "focus_sectors": ["Enterprise SaaS", "AI", "Developer Tools"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Enterprise AI and developer tools focused VC.", "source": "curated"},
    {"name": "Emergence Growth", "website": "https://www.emcap.com/growth", "focus_sectors": ["Enterprise SaaS", "AI"], "stage_preference": ["growth"], "check_size_min": 20000, "check_size_max": 100000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Emergence Capital's growth equity practice.", "source": "curated"},
    {"name": "Elad Gil", "website": "https://eladgil.com", "focus_sectors": ["AI", "SaaS", "Consumer", "Fintech"], "stage_preference": ["seed", "series-a"], "check_size_min": 250, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": ["Stripe", "Airbnb", "OpenAI", "Airtable"], "description": "Prolific solo investor and operator.", "source": "curated"},
    {"name": "DST Global", "website": "https://dst.global", "focus_sectors": ["Technology", "Consumer", "Fintech", "E-commerce"], "stage_preference": ["series-b", "growth"], "check_size_min": 50000, "check_size_max": 5000000, "geo_focus": ["Global"], "notable_portfolio": ["Facebook", "Twitter", "Spotify", "Airbnb", "Klarna"], "description": "Yuri Milner's global late-stage technology fund.", "source": "curated"},
    {"name": "Wellington Management Ventures", "website": "https://wellington.com", "focus_sectors": ["Technology", "Healthcare", "Financial Services"], "stage_preference": ["growth"], "check_size_min": 50000, "check_size_max": 1000000, "geo_focus": ["Global"], "notable_portfolio": [], "description": "Wellington's crossover venture investment practice.", "source": "curated"},
    {"name": "Transformation Capital", "website": "https://transformationcapital.com", "focus_sectors": ["Healthcare IT", "Digital Health", "Life Sciences"], "stage_preference": ["series-a", "series-b"], "check_size_min": 5000, "check_size_max": 50000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Healthcare technology focused growth equity.", "source": "curated"},
    {"name": "Novo Holdings Ventures", "website": "https://novoholdings.dk/investments/ventures", "focus_sectors": ["Life Sciences", "Biotech", "Healthcare"], "stage_preference": ["series-a", "series-b", "growth"], "check_size_min": 10000, "check_size_max": 200000, "geo_focus": ["Global"], "notable_portfolio": [], "description": "Novo Nordisk Foundation's life sciences venture arm.", "source": "curated"},
    {"name": "Khosla Impact", "website": "https://khoslaventures.com/impact", "focus_sectors": ["Climate", "Agriculture", "Water", "Energy Access"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 10000, "geo_focus": ["Global", "Emerging Markets"], "notable_portfolio": [], "description": "Khosla Ventures' impact investing arm.", "source": "curated"},
    {"name": "NewLimit", "website": "https://newlimit.com", "focus_sectors": ["Longevity", "Biotech", "Aging"], "stage_preference": ["seed", "series-a"], "check_size_min": 1000, "check_size_max": 20000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Brian Armstrong-backed longevity and aging biotech investor.", "source": "curated"},
    {"name": "Acme Capital", "website": "https://acmecap.com", "focus_sectors": ["Consumer", "Enterprise", "SaaS", "Marketplace"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Early-stage generalist VC fund.", "source": "curated"},
    {"name": "Bullpen Capital", "website": "https://bullpencap.com", "focus_sectors": ["Consumer", "Enterprise", "Marketplace", "SaaS"], "stage_preference": ["series-a"], "check_size_min": 1000, "check_size_max": 7000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Post-seed bridge fund filling the Series A gap.", "source": "curated"},
    {"name": "ClearBridge Investments", "website": "https://clearbridge.com", "focus_sectors": ["Technology", "Healthcare", "Fintech"], "stage_preference": ["growth"], "check_size_min": 20000, "check_size_max": 500000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Franklin Templeton's growth equity investment arm.", "source": "curated"},
    {"name": "Renegade Partners", "website": "https://renegade.vc", "focus_sectors": ["Consumer", "SaaS", "Healthcare"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Contrarian seed and Series A fund.", "source": "curated"},
    {"name": "Thrive Capital", "website": "https://thrivecap.com", "focus_sectors": ["Technology", "SaaS", "Consumer", "Fintech"], "stage_preference": ["series-b", "growth"], "check_size_min": 10000, "check_size_max": 500000, "geo_focus": ["United States"], "notable_portfolio": ["Instagram", "Spotify", "GitHub", "Robinhood"], "description": "Josh Kushner's growth-stage technology fund.", "source": "curated"},
    {"name": "IVP Growth", "website": "https://ivp.com", "focus_sectors": ["SaaS", "Consumer Internet", "Fintech"], "stage_preference": ["growth"], "check_size_min": 50000, "check_size_max": 500000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "IVP's late-stage growth equity practice.", "source": "curated"},
    {"name": "Breyer Capital", "website": "https://breyercapital.com", "focus_sectors": ["AI", "Consumer", "Healthcare", "Enterprise"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 1000, "check_size_max": 20000, "geo_focus": ["United States", "China"], "notable_portfolio": ["Facebook", "Marvel", "Hulu"], "description": "Jim Breyer's personal venture firm with early Facebook investment.", "source": "curated"},
    {"name": "Scout Fund by Sequoia", "website": "https://sequoiacap.com/scouts", "focus_sectors": ["Technology", "Consumer", "Enterprise"], "stage_preference": ["pre-seed"], "check_size_min": 25, "check_size_max": 250, "geo_focus": ["Global"], "notable_portfolio": [], "description": "Sequoia Capital's founder scout program.", "source": "curated"},
    {"name": "Lowercase Capital", "website": "https://lowercase.vc", "focus_sectors": ["Consumer", "SaaS", "Mobile"], "stage_preference": ["seed"], "check_size_min": 100, "check_size_max": 1000, "geo_focus": ["United States"], "notable_portfolio": ["Twitter", "Uber", "Instagram"], "description": "Chris Sacca's personal early-stage fund.", "source": "curated"},
    {"name": "Gradient Ventures (Google)", "website": "https://gradient.com", "focus_sectors": ["AI", "Machine Learning", "Enterprise AI"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 10000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Google's dedicated AI startup fund.", "source": "curated"},
    {"name": "Rock Springs Capital", "website": "https://rockspringscapital.com", "focus_sectors": ["Healthcare", "Biotech", "Medical Devices"], "stage_preference": ["growth"], "check_size_min": 10000, "check_size_max": 200000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Healthcare crossover fund.", "source": "curated"},
    {"name": "SoftBank Latin America Fund", "website": "https://softbank.com/latam", "focus_sectors": ["Technology", "Fintech", "Consumer", "Logistics"], "stage_preference": ["series-a", "series-b", "growth"], "check_size_min": 5000, "check_size_max": 200000, "geo_focus": ["Latin America"], "notable_portfolio": ["OLX", "Loggi", "Gympass"], "description": "SoftBank's dedicated Latin America innovation fund.", "source": "curated"},
    {"name": "Globant Ventures", "website": "https://ventures.globant.com", "focus_sectors": ["AI", "Enterprise SaaS", "Digital Transformation"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["Latin America", "United States"], "notable_portfolio": [], "description": "Globant's corporate venture arm.", "source": "curated"},
    {"name": "HealthX Ventures", "website": "https://healthx.com", "focus_sectors": ["Digital Health", "Healthcare AI", "Wellness", "Insurance Tech"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Digital health focused seed and Series A VC.", "source": "curated"},
    {"name": "SpringRock Ventures", "website": "https://springrock.vc", "focus_sectors": ["Healthcare", "Life Sciences", "Digital Health"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 5000, "geo_focus": ["United States"], "notable_portfolio": [], "description": "Healthcare innovation seed fund.", "source": "curated"},
    {"name": "Lakestar", "website": "https://www.lakestar.com", "focus_sectors": ["Consumer", "Enterprise SaaS", "Fintech", "Deep Tech"], "stage_preference": ["seed", "series-a", "series-b"], "check_size_min": 1000, "check_size_max": 30000, "geo_focus": ["Europe", "Global"], "notable_portfolio": ["Skype", "Facebook (early)", "Airbnb", "Spotify"], "description": "European VC with global portfolio co-founded by Skype co-founder Klaus Hommels.", "source": "curated"},
    {"name": "Breega", "website": "https://breega.com", "focus_sectors": ["SaaS", "Fintech", "Healthcare", "Deep Tech"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 10000, "geo_focus": ["Europe", "France"], "notable_portfolio": [], "description": "French VC with European scope.", "source": "curated"},
    {"name": "Isomer Capital", "website": "https://isomercapital.com", "focus_sectors": ["Technology", "Deep Tech", "AI", "SaaS"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 10000, "geo_focus": ["Europe"], "notable_portfolio": [], "description": "London-based fund of funds and co-investor.", "source": "curated"},
    {"name": "Cherry Ventures", "website": "https://cherry.vc", "focus_sectors": ["Consumer", "SaaS", "Fintech", "Deep Tech"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 250, "check_size_max": 3000, "geo_focus": ["Europe", "Germany"], "notable_portfolio": [], "description": "Berlin-based early-stage VC fund.", "source": "curated"},
    {"name": "Earlybird Venture Capital", "website": "https://earlybird.com", "focus_sectors": ["SaaS", "AI", "Fintech", "Healthcare", "Deep Tech"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 10000, "geo_focus": ["Europe"], "notable_portfolio": ["UiPath", "N26", "Wefox"], "description": "Pan-European multi-stage VC.", "source": "curated"},
    {"name": "Project A Ventures", "website": "https://project-a.com", "focus_sectors": ["B2B SaaS", "Consumer", "Fintech", "Deep Tech"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 10000, "geo_focus": ["Europe", "Germany"], "notable_portfolio": [], "description": "Berlin-based operational VC providing hands-on support.", "source": "curated"},
    {"name": "Inreach Ventures", "website": "https://www.inreachventures.com", "focus_sectors": ["SaaS", "B2B", "AI", "Fintech"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 250, "check_size_max": 3000, "geo_focus": ["Europe"], "notable_portfolio": [], "description": "European AI-driven VC sourcing firm.", "source": "curated"},
    {"name": "Mangrove Capital Partners", "website": "https://www.mangrove.vc", "focus_sectors": ["Consumer", "Enterprise SaaS", "AI", "Fintech"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 10000, "geo_focus": ["Europe"], "notable_portfolio": ["Skype", "wuala", "Algolia"], "description": "Luxembourg and London based early-stage European VC.", "source": "curated"},
    {"name": "United First Partners", "website": "https://ufp.com", "focus_sectors": ["Technology", "Fintech", "Healthcare"], "stage_preference": ["growth"], "check_size_min": 20000, "check_size_max": 200000, "geo_focus": ["Europe"], "notable_portfolio": [], "description": "European growth equity investor.", "source": "curated"},
    {"name": "Nauta Capital", "website": "https://nautacapital.com", "focus_sectors": ["SaaS", "AI", "Marketplace", "Fintech"], "stage_preference": ["series-a", "series-b"], "check_size_min": 2000, "check_size_max": 15000, "geo_focus": ["Europe", "Spain", "UK"], "notable_portfolio": [], "description": "European B2B SaaS growth investor.", "source": "curated"},
    {"name": "Speedinvest", "website": "https://speedinvest.com", "focus_sectors": ["Fintech", "Deeptech", "SaaS", "Consumer"], "stage_preference": ["pre-seed", "seed"], "check_size_min": 250, "check_size_max": 3000, "geo_focus": ["Europe"], "notable_portfolio": [], "description": "Vienna-based European pre-seed and seed fund.", "source": "curated"},
    {"name": "Iris Capital", "website": "https://www.iris.capital", "focus_sectors": ["Digital", "Software", "Internet"], "stage_preference": ["series-a", "series-b"], "check_size_min": 2000, "check_size_max": 20000, "geo_focus": ["Europe", "Middle East"], "notable_portfolio": [], "description": "European digital economy growth investor.", "source": "curated"},
    {"name": "360 Capital Partners", "website": "https://360capital.vc", "focus_sectors": ["SaaS", "Fintech", "Deep Tech"], "stage_preference": ["seed", "series-a"], "check_size_min": 500, "check_size_max": 7000, "geo_focus": ["Europe", "France", "Italy"], "notable_portfolio": [], "description": "Franco-Italian early-stage VC.", "source": "curated"},
    {"name": "Stride VC", "website": "https://stride.vc", "focus_sectors": ["B2B SaaS", "Enterprise", "Developer Tools"], "stage_preference": ["seed"], "check_size_min": 250, "check_size_max": 2500, "geo_focus": ["Europe", "United Kingdom"], "notable_portfolio": [], "description": "London-based B2B enterprise seed fund.", "source": "curated"},
    {"name": "Idinvest Digital", "website": "https://idinvest.com", "focus_sectors": ["SaaS", "Consumer", "Digital Media"], "stage_preference": ["series-a", "series-b"], "check_size_min": 3000, "check_size_max": 30000, "geo_focus": ["France", "Europe"], "notable_portfolio": [], "description": "French growth equity firm.", "source": "curated"},
    {"name": "Draper Esprit", "website": "https://draperesprit.com", "focus_sectors": ["Consumer", "Enterprise SaaS", "Deep Tech", "Fintech"], "stage_preference": ["series-a", "series-b"], "check_size_min": 2000, "check_size_max": 30000, "geo_focus": ["Europe"], "notable_portfolio": [], "description": "Listed European growth-stage technology VC.", "source": "curated"},
    {"name": "Molten Ventures (formerly Draper Esprit)", "website": "https://moltenventures.com", "focus_sectors": ["Consumer", "SaaS", "Deep Tech", "Security"], "stage_preference": ["series-a", "series-b"], "check_size_min": 2000, "check_size_max": 30000, "geo_focus": ["Europe"], "notable_portfolio": ["Ledger", "Spirit Energy", "Coachhub"], "description": "London-listed European growth VC formerly known as Draper Esprit.", "source": "curated"},
]


def main():
    print(f"Batch 3: {len(BATCH3)} records")
    seen = set()
    deduped = [r for r in BATCH3 if r["name"].lower() not in seen and not seen.add(r["name"].lower())]
    print(f"After dedup: {len(deduped)}")

    total = 0
    for i in range(0, len(deduped), 50):
        loaded = upsert_vcs(deduped[i:i+50])
        total += loaded
        print(f"  Batch {i//50+1}: +{loaded}")

    print(f"Batch 3 done: {total}")

    h = {"apikey": SERVICE_ROLE_KEY, "Authorization": f"Bearer {SERVICE_ROLE_KEY}", "Prefer": "count=exact"}
    resp = requests.head(f"{SUPABASE_URL}/rest/v1/vcs?select=count", headers=h, timeout=10)
    print(f"Total: {resp.headers.get('content-range', 'unknown')}")


if __name__ == "__main__":
    main()
